### ISSUE TITLE
I need 15 lang translation of everything

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#1]
_From @amitabhm21 on November 8, 2017 22:12_

oijusoifjslakdjflkas jlaskdfj 

_Copied from original issue: Microsoft/Access2Justice#1_

**Comment by aroubin** [comment]
_From @amitabhm21 on November 8, 2017 22:13_

I love this can you add 50 more lang? @shandang

**Comment by aroubin** [comment]
_From @amitabhm21 on November 13, 2017 18:51_

Closing test issue

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
