### ISSUE TITLE
Feature/scaffold solution structure v2

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#10]
_From @alaatadmori on April 20, 2018 16:50_

created a new solution structure based on the input from Amitabh and Andrew.

_Copied from original issue: Microsoft/Access2Justice/pull/10_

**Comment by aroubin** [comment]
_From @msftclas on April 20, 2018 16:50_

[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/Microsoft/Access2Justice?pullRequest=10) <br/>All CLA requirements met.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
