### ISSUE TITLE
Still seeing <br> displayed in some Guided Assists.

### ISSUE THREAD

**Issue by grawdon** [LSCOIT/LegalNavigator#1004]

**Comment by grawdon** [comment]
![image](https://user-images.githubusercontent.com/46725623/66048759-c0888580-e4ef-11e9-89e7-41d6103367a0.png)

**Comment by yevhenobertas** [comment]
@KellyeDC , @svasylenko 
1-3 hours investigation of importing data related to the task
2-4 hours development
1-2 hours testing

There are couple of ways for implementing that.
Best way would be to fix that using some custom validation helper. @KellyeDC Do you agree?

**Comment by KellyeDC-zz** [comment]
After today’s discussion with issue initiating in 2J Author please confirm estimates.

Kellye Bennett
Legal Navigator Project Manager
Legal Services Corporation
_____________________________________________________________________
Office of Information Technology
3333 K Street, NW
Washington, DC 20007
P: 202.295.1569
M: 703.889.7288
E: bennettk@lsc.gov
________________________________

**Comment by yevhenobertas** [comment]
@KellyeDC , Fixed on the development environment

**Comment by grawdon** [comment]
This problem was resolved. The <br> was no longer there.
