### ISSUE TITLE
As Portal User, I want to read about a specific topic (e.g. Eviction) to get a broad understanding of the resources and organizations that are available to me for help.   

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#101]
_From @czdiana2321 on June 4, 2018 20:19_

USER-> Directory/Topics
Acceptance Criteria:
1. Portal User is able to view the content about specific topic
2. The system is able to provide details about specific legal topic.
3. Information is displayed using the Topics Landing pate template design. 

_Copied from original issue: Microsoft/Access2Justice#124_

**Comment by yfzwinnie** [comment]
Completed as part of MVP.

**Comment by KellyeDC-zz** [comment]
@grawdon Have the states had the opportunity to approve/confirm?

**Comment by grawdon** [comment]
@KellyeDC I believe they can do that now. They could start with an overview of eviction and then have more specific resources below. 

![image](https://user-images.githubusercontent.com/46725623/57230405-e9a6f780-6fdd-11e9-98a5-3e6f50862ffd.png)
