### ISSUE TITLE
As Portal User, I need to review information about an organization, such as general info, location and business hours.  

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#102]
_From @czdiana2321 on June 4, 2018 20:27_

USER-> Directory/Topics
Acceptance Criteria:
1. Portal User is able to review the general information, location and business hours of an organization. 
2. Information is displayed according the resources design templates. 

_Copied from original issue: Microsoft/Access2Justice#125_

**Comment by yfzwinnie** [comment]
Completed as part of MVP.

**Comment by KellyeDC-zz** [comment]
@grawdon Have the states had the opportunity to review/confirm?

**Comment by grawdon** [comment]
@KellyeDC I have not done this with the states. Maybe we should isolate all of  user stories dealing with content display format and review  with the states to be sure how LN is displaying information now meets the needs of the user. To me they seem to, but the states might think differently.
