### ISSUE TITLE
Money, Debt, and Consumer Issues is not showing as a parent topic

### ISSUE THREAD

**Issue by KellyeDC** [LSCOIT/LegalNavigator#1023]
Money, Debt, and Consumer Issues is not showing as a parent topic

Version [17.1]

Reported by Alex Forger 1/7/2020

**Comment by ozholob** [comment]
Hello, @KellyeDC fixed on dev: 
![image](https://user-images.githubusercontent.com/55988406/72261349-4e126000-361d-11ea-8f8d-7bf0ae2ba67b.png)

**Comment by grawdon** [comment]
@KellyeDC It is showing up now.
