### ISSUE TITLE
Child topic is rendering as a parent (Domestic Violence and Abuse)  in STG

### ISSUE THREAD

**Issue by KellyeDC** [LSCOIT/LegalNavigator#1024]
Child topic is rendering as a parent (Domestic Violence and Abuse) in STG

Reported by Alex Forger 1/12020

**Comment by ozholob** [comment]
Hi! @KellyeDC Fixed on dev, as well on stage. 
![image](https://user-images.githubusercontent.com/55988406/72261211-10153c00-361d-11ea-94bd-16ebed6878fe.png)

**Comment by grawdon** [comment]
@KellyeDC  It is not showing up as parent in dev, so I am assuming this will be fixed with DEV is pushed to STG.
