### ISSUE TITLE
Provide list of new icons urls for Hawaii.  Update in Slack #content-hawaii

### ISSUE THREAD

**Issue by KellyeDC** [LSCOIT/LegalNavigator#1033]
Provide list of new icons urls for Hawaii.  Update in Slack #content-hawaii.  These also need to be added to the latest topics spreadsheet that is loaded.

**Comment by yevhenobertas** [comment]
Done. It was done May 20-th the last time. The list was provided to Andres

**Comment by yevhenobertas** [comment]
Done. It was done May 20-th the last time. The list was provided to Andres
