### ISSUE TITLE
Inconsistent ranking of resources for Hawaii - details in Slack #content-hawaii

### ISSUE THREAD

**Issue by KellyeDC** [LSCOIT/LegalNavigator#1034]
Slack Reference: Administrative Agency Hearings: This is for zip code 96813. On Stage they are ranked 1) Legal Aid Society of Hawaii, 2) Hawaii Online Pro Bono Free Legal Answers, 3) Hawaii Disability Rights Center, 4) HSBA Lawyer Referral Service, 5) HSBA Legal Line. On the spreadsheet they are ranked: 1) Legal Aid Society of Hawaii. 2) HSBA Lawyer Referral Service, 3) Hawaii Online Pro Bono Free Legal Answers, 4) HSBA Legal Line, 5) Hawaii Disability Rights Center

**Comment by yevhenobertas** [comment]
@KellyeDC Done. Please review.
