### ISSUE TITLE
As Portal User, I want to view organization on the map view so that I can plan my route there.  

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#104]
_From @czdiana2321 on June 4, 2018 20:36_

USER-> Directory/Topics
Acceptance Criteria:
1. The system is able to provide the location map view of the organization
2. Portal User is able to view the location map view of the organization  

_Copied from original issue: Microsoft/Access2Justice#127_

**Comment by yfzwinnie** [comment]
Completed as part of MVP.

**Comment by breeglej** [comment]
@KellyeDC @grawdon - I don't know how to test this.  Where is there an organization that can show on a map?

**Comment by grawdon** [comment]
@KellyeDC @breeglej Isn't this the same as issue 467?
