### ISSUE TITLE
Change header/footer "Privacy Promise" to "Privacy Notice " on Home page

### ISSUE THREAD

**Issue by KellyeDC** [LSCOIT/LegalNavigator#1040]
Change header/footer "Privacy Promise" to "Privacy Notice " on Home page

**Comment by yevhenobertas** [comment]
Ready for review on Dev. and Stage env.

**Comment by yevhenobertas** [comment]
@KellyeDC @grawdon @svasylenko

**Comment by yevhenobertas** [comment]
@KellyeDC Ready for review on both Dev and Stage envs.
