### ISSUE TITLE
Hide sidebar (3 organization) featured on topics/resources screen for both states

### ISSUE THREAD

**Issue by KellyeDC** [LSCOIT/LegalNavigator#1045]
Hide sidebar (3 organization) featured on topics/resources screen for both states

**Comment by grawdon** [comment]
@KellyeDC @svasylenko So there is no confusion, it is the box on the lower right side of the screen that shows organizations. Here is a screenshot: 
![image](https://user-images.githubusercontent.com/46725623/75920458-04781180-5e25-11ea-9cd9-8bf88ba1bcf2.png)

**Comment by yevhenobertas** [comment]
@KellyeDC Ready for review on both Dev and Stage envs.
