### ISSUE TITLE
Remove organizations at bottom of the action plan when initially generated

### ISSUE THREAD

**Issue by KellyeDC** [LSCOIT/LegalNavigator#1047]
Remove organizations at bottom of the action plan when initially generated

**Comment by svasylenko** [comment]
Implemented on dev. Awaits approval for deployment to Stage. @KellyeDC

**Comment by grawdon** [comment]
@KellyeDC @yevhenobertas I have verified the organizations at the bottom have been removed when an action plan is first generated.
