### ISSUE TITLE
Research how to pass application configuration variables without hardcoding it.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#106]
_From @yfzwinnie on June 4, 2018 21:23_

Need to see if we can make the api endpoints to be dynamic instead of hardcoding the domain everytime.

Example: http://access2justiceapi.azurewebsites.net/api/curatedexperience?surveyId=0b7dfe9b-cec9-4490-b768-c40916d52382

Should be: /api/curatedexperience?surveyId=0b7dfe9b-cec9-4490-b768-c40916d52382

_Copied from original issue: Microsoft/Access2Justice#129_

**Comment by aroubin** [comment]
_From @yfzwinnie on June 20, 2018 0:42_

See PR #162. Code review with Andrew and merged pull request into develop.

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
