### ISSUE TITLE
Feature/scaffold ui

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#11]
_From @yfzwinnie on May 2, 2018 21:16_

adding the latest UI changes

_Copied from original issue: Microsoft/Access2Justice/pull/11_

**Comment by aroubin** [comment]
_From @msftclas on May 2, 2018 21:17_

[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/Microsoft/Access2Justice?pullRequest=11) <br/>All CLA requirements met.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
