### ISSUE TITLE
As State Admin, I need to edit static content for my state

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#114]
_From @czdiana2321 on June 7, 2018 21:0_

Each state (Organizational Unit) will have default content showing up unless state admins create a customized version for their state. 

- User chooses the content to update (e.g. Home Page)
- User turns on Edit mode on the page being edited 
- The system checks that:
   ~ the user is logged in 
   ~ their role allows them to edit content
   ~ they belong to OU through their role membership that maps to the OU where the content is being edited. 
- User makes the changes to the content and submits them
- The system API makes sure that user is allowed to perform the change (just like above) and persists it. 
- New content shows up on the site. 

_Copied from original issue: Microsoft/Access2Justice#140_

**Comment by aroubin** [comment]
Re-purposed this story for static content editing.

**Comment by aroubin** [comment]
_From @yfzwinnie on November 5, 2018 17:33_

The admin UI has been created. Will be creating separate tasks for each static content pages. Moving this to resolved.

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
