### ISSUE TITLE
Create few unit test samples, based on best practices, to serve as a blueprint for our unit testing.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#115]
_From @alaatadmori on June 8, 2018 19:4_

Our current implementation of the unit testing is improper (mostly because it hits actual external resources (DB/LUIS..) instead of mocking them). We need to create some robust samples and come up with a good naming convention to maintain consistency across the board.

_Copied from original issue: Microsoft/Access2Justice#141_

**Comment by aroubin** [comment]
_From @alaatadmori on June 13, 2018 6:21_

I created some samples (CosmosDb Tests project) and code reviewed them with Andrew. We also created a simple convention that will help us maintain consistency:

```
[Fact]
public void NameOfTheMethodUnderTestShouldDoExpectedOutcome()
{
    // Arrange
    // setup test data
 
    // Act
    // execute the methods under tests
 
    // Assert
    // verify expected outcome
}
```

- the name of the method always reads this [Method Name]Should[Do something]

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
