### ISSUE TITLE
Feature/visual designs

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#118]
_From @yfzwinnie on June 14, 2018 0:47_

Merging latest visual designs for home page. 

_Copied from original issue: Microsoft/Access2Justice/pull/146_

**Comment by aroubin** [comment]
_From @yfzwinnie on June 14, 2018 23:41_

Completed code review with Andrew and merge code into develop.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
