### ISSUE TITLE
As a Portal User, I need to state my issue in plain terms so that I can be directed to the right help/resources

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#12]
_From @czdiana2321 on May 3, 2018 0:58_

#18 Create LUIS App (US#12)
#19 Create UI for Search (US#12)
#20 Create UI for Search Results (US#12)
#29 Create backend service for search (US#12)
#30 Create ability to fetch intents from LUIS (US#12)
#31 Create resource storage (US#12)
#32 Create schema for mapping the intents (US#12)
#35 Enable swagger (US#12)
#47 Create backend service for search results

_Copied from original issue: Microsoft/Access2Justice#12_

**Comment by aroubin** [comment]
_From @yfzwinnie on June 5, 2018 23:38_

Code review with Alaa and Andrew completed. Moving to Resolve.

**Comment by aroubin** [comment]
_From @amitabhm21 on June 13, 2018 19:32_

This is good for MVP. We need to continue to make the intent engine better beyond MVP

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
