### ISSUE TITLE
The system should be able to map intent to conceptual legal entities that user will be interacting with. 

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#120]
_From @czdiana2321 on June 15, 2018 1:51_

_Copied from original issue: Microsoft/Access2Justice#149_

**Comment by breeglej** [comment]
@KellyeDC  - Not needed for pilot.  This is an enhancement.

**Comment by KellyeDC-zz** [comment]
Not sure of intent for this user story.
