### ISSUE TITLE
Spike: Investigate Potential A2JAuthor Integration

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#123]
_From @aroubin on June 15, 2018 2:36_

Investigate feasibility of importing A2JAuthor guided interview definition json files into A2J curated experience graph. 

Acceptance Criteria:
- A2JAuthor file is accepted by the import process
- All questions in sequence are created (using default text prompts)
- Branching / looping is supported (through logical expressions or button actions)
- Variables defined in the guided interview are used as tags for resource and topic search.
 

_Copied from original issue: Microsoft/Access2Justice#153_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
