### ISSUE TITLE
The NLP intent engine should be able to identify multiple probable intents based on accuracy score. 

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#126]
_From @czdiana2321 on June 15, 2018 17:35_

_Copied from original issue: Microsoft/Access2Justice#156_

**Comment by yfzwinnie** [comment]
Completed as part of MVP.

**Comment by KellyeDC-zz** [comment]
@grawdon Should we get David to take a look at this to confirm?

**Comment by breeglej** [comment]
@KellyeDC @grawdon - I'm not sure we should do any more work on this.  David has already said that the NLP engine is not suitable and he is building a new one.

**Comment by KellyeDC-zz** [comment]
Resolved
