### ISSUE TITLE
As Portal User, I want to learn about the safe way to exit the site quickly, so that others don't know about me accessing the site.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#129]
_From @czdiana2321 on June 15, 2018 17:38_

_Copied from original issue: Microsoft/Access2Justice#159_

**Comment by svasylenko** [comment]
It seems we either should advice anonymous visiting via Chrome or add instructions how to use VPN.

**Comment by KellyeDC-zz** [comment]
KB Reviewed - Not required.
