### ISSUE TITLE
As a Portal User, I want to chat with a Guided assistant so that I can be shown all support options that are available specifically for me.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#13]
_From @czdiana2321 on May 3, 2018 1:2_

#37 Create basic CRUD operations of the Cosmos DB
#34 Create console app to create and map questions for curated experience
#38 Create ability to map intent to conceptual legal entities that user will be 
#21 Create UI for Guided Assistant

_Copied from original issue: Microsoft/Access2Justice#13_

**Comment by aroubin** [comment]
_From @alaatadmori on May 3, 2018 20:55_

Create basic CRUD operations of the Cosmos DB #37.

**Comment by aroubin** [comment]
_From @alaatadmori on May 30, 2018 4:50_

I'm moving this user story to Resolved as we now have a similar, more descriptive story in the ToDo bucket (#15). This user story was relevant when we were discussing the architecture and design of the application but we now have more specific requirements/expectations that we could write tasks for.

I also moved 2 of the tasks (#22 #24) that were linked to this story to the new user story (#15) where they are directly related.

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh
