### ISSUE TITLE
As a Portal User, I want to click the "Our Privacy Promise" link, so that I understand the privacy policy regarding my personal information. 

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#130]
_From @czdiana2321 on June 15, 2018 17:44_

_Copied from original issue: Microsoft/Access2Justice#160_

**Comment by yfzwinnie** [comment]
Completed as part of MVP.

**Comment by breeglej** [comment]
@KellyeDC @grawdon  - While it appears that the functionality is working correctly, we still need to add an actual privacy promise.

**Comment by grawdon** [comment]
@KellyeDC @breeglej Yes. As to functionality, this issue is complete.
