### ISSUE TITLE
Create a converter for the "A2J Author Guided Interview" to "Access2Justice Curated Experience".

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#134]
_From @alaatadmori on June 19, 2018 21:13_

We need an endpoint that allow us to convert the raw schema of A2J Author to a Curated Experience compatible schema.

_Copied from original issue: Microsoft/Access2Justice#165_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
