### ISSUE TITLE
Implement storage for personalized plan in user profile. (US #91)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#143]
_From @aroubin on June 26, 2018 19:3_

#91 
Implement storage in Cosmos DB to associate personalized plan json with user ID that we get from Outlook.

_Copied from original issue: Microsoft/Access2Justice#178_

**Comment by svasylenko** [comment]
Verified. First picture: User with personalized action plan ID, second - that Action Plan ID.

![image](https://user-images.githubusercontent.com/46557859/51607386-282c1100-1f1d-11e9-9208-ee0e544b9fd4.png)

![image](https://user-images.githubusercontent.com/46557859/51607432-485bd000-1f1d-11e9-872b-173b8709e5af.png)
