### ISSUE TITLE
As a Portal User, I need to respond to questions in the curated experience so that I can provide correct information about my specific circumstances.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#15]
_From @czdiana2321 on May 3, 2018 1:4_

#22 Create Guided Assistant Service
#24 Create Curated Business Logic
#258 Build Curated Experience Plan.

_Copied from original issue: Microsoft/Access2Justice#15_

**Comment by svasylenko** [comment]
Verified.

![image](https://user-images.githubusercontent.com/46557859/51616859-ae535200-1f33-11e9-82f7-bbf6d71fa1e8.png)
