### ISSUE TITLE
Feature/personalized action plan

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#168]
_From @charmila-c on July 9, 2018 11:38_

Raised Pull request for below tasks as all are related to Personalized plan.
#183 
#211 
#179 

_Copied from original issue: Microsoft/Access2Justice/pull/217_

**Comment by aroubin** [comment]
_From @alaatadmori on July 16, 2018 16:42_

Hi Charmila, please merge conflicts and push again. Thank you.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
