### ISSUE TITLE
test project for logger

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#169]
_From @kapilzen on July 9, 2018 19:11_

added test project for logger

_Copied from original issue: Microsoft/Access2Justice/pull/218_

**Comment by aroubin** [comment]
_From @kapilzen on July 9, 2018 19:36_

I am not able to figure out the Assert part as its logging, I will check for proper case to use assert.

**Comment by aroubin** [comment]
_From @kapilzen on August 13, 2018 16:36_

will raise another one

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
