### ISSUE TITLE
Feature/174 login backend

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#170]
_From @vennasr on July 10, 2018 13:59_

Implemented login functionality and after successful login inserting the user basic data in to cosmos db. 

To test the functionality application has to be registered in the application registration portal( https://apps.dev.microsoft.com). 
Copy the application id value in client id section in the config file
Generate new password and copy the value in the client secret section in the config file.
Update the Redirect URI as <webapiurl>/signin-microsoft
Ex: http://localhost:61726/signin-microsoft

_Copied from original issue: Microsoft/Access2Justice/pull/220_

**Comment by aroubin** [comment]
_From @msftclas on July 10, 2018 14:0_

[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/Microsoft/Access2Justice?pullRequest=220) <br/>All CLA requirements met.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
