### ISSUE TITLE
Save Resources to User Profile

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#171]
_From @charmila-c on July 11, 2018 12:27_

_Copied from original issue: Microsoft/Access2Justice#221_

**Comment by aroubin** [comment]
_From @yfzwinnie on July 24, 2018 15:38_

Code reviewed between Alaa and I. Moving to resolved.

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
