### ISSUE TITLE
If user is not logged in, we need to redirect user to login page before saving resource

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#172]
_From @charmila-c on July 11, 2018 12:43_

_Copied from original issue: Microsoft/Access2Justice#223_

**Comment by aroubin** [comment]
_From @turpu-rakesh on July 18, 2018 5:57_

we have created separate task for private window issue for session storage.

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
