### ISSUE TITLE
Feature/save resources to profile

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#176]
_From @charmila-c on July 12, 2018 8:45_

#221 

_Copied from original issue: Microsoft/Access2Justice/pull/228_

**Comment by aroubin** [comment]
_From @alaatadmori on July 20, 2018 20:13_

Closing this PR as it was merged to the other open one #264 .

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
