### ISSUE TITLE
Create LUIS App (US#12)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#18]
_From @czdiana2321 on May 3, 2018 6:17_

_Copied from original issue: Microsoft/Access2Justice#18_

**Comment by aroubin** [comment]
_From @alaatadmori on May 17, 2018 6:4_

@vennasr can you please check with @amitabhm21 and resolve this task? We are using the Luis app that Amitabh shared so I believe we don't need to create a new one. Thank you.

+ @aroubin for visibility.

**Comment by aroubin** [comment]
_From @alaatadmori on May 22, 2018 16:54_

Moving this to resolved as we are using the existing Luis App that Amitabh created.

**Comment by yfzwinnie** [comment]
Completed during MVP and closed by Amitabh
