### ISSUE TITLE
Implemented Jasmine testcases for SearchFilterPipe (#190)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#180]
_From @venkati-naidu on July 13, 2018 11:27_

Please review the Jasmine test case for  SearchFilterPipe and provide your comments

_Copied from original issue: Microsoft/Access2Justice/pull/232_

**Comment by aroubin** [comment]
_From @venkati-naidu on July 18, 2018 14:32_

Review comments fixed along with new test cases for sorting the items

**Comment by aroubin** [comment]
_From @venkati-naidu on July 19, 2018 6:28_

Created new PR "190_SearchPipeUnitTests review changes merged with Develop #260 "
i.e. Ref: #232 - Review comments fixed and merged with latest Develop branch. Hence cancelling the #232 to avoid the confusion.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
