### ISSUE TITLE
[SearchResults] Page Refresh is not retaining the data, blank page is displaying.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#184]
_From @turpu-rakesh on July 16, 2018 6:43_

On refreshing the search page it is displaying blank page.

_Copied from original issue: Microsoft/Access2Justice#237_

**Comment by aroubin** [comment]
_From @kapilzen on August 15, 2018 18:51_

looks good

**Comment by svasylenko** [comment]
[Jan 18, 2019 12_08 PM.zip](https://github.com/LSCOIT/LegalNavigator/files/2772489/Jan.18.2019.12_08.PM.zip)

**Comment by KellyeDC-zz** [comment]
@svasylenko Were you able to reproduce this defect?  I believe this needs to be revisited.  Please confirm.

**Comment by Olgaivchenko** [comment]
@KellyeDC 
Issue isn't reproduced, so it can be closed.
