### ISSUE TITLE
Redirect to the same page after login

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#186]
_From @vennasr on July 16, 2018 7:23_

1) Added code to redirect to the same page when user clicks on during login.
2) Added code to redirect to home page during logout.

Task# 223 - Redirection process completed. For save details related flow Rakesh will raise another PR.

_Copied from original issue: Microsoft/Access2Justice/pull/239_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
