### ISSUE TITLE
Create UI for Search (US#12)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#19]
_From @czdiana2321 on May 3, 2018 6:22_

_Copied from original issue: Microsoft/Access2Justice#19_

**Comment by aroubin** [comment]
_From @venkati-naidu on May 3, 2018 12:1_

assigned to me

**Comment by aroubin** [comment]
_From @yfzwinnie on June 5, 2018 23:38_

Code review with Alaa and Andrew completed. Moving to Resolve.

**Comment by aroubin** [comment]
_From @amitabhm21 on June 13, 2018 19:10_

Hits MVP scenarios

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
