### ISSUE TITLE
Feature/222 remove saved resources from profile

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#190]
_From @charmila-c on July 17, 2018 10:31_

#222 

_Copied from original issue: Microsoft/Access2Justice/pull/246_

**Comment by aroubin** [comment]
_From @alaatadmori on July 20, 2018 20:14_

Closing this PR as it was merged to the other open one #264 .

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
