### ISSUE TITLE
User profile should be updated/refreshed on removing a resource from My plan or My Saved Resources

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#191]
_From @charmila-c on July 17, 2018 10:34_

_Copied from original issue: Microsoft/Access2Justice#247_

**Comment by svasylenko** [comment]
[Jan 18, 2019 3_57 PM.zip](https://github.com/LSCOIT/LegalNavigator/files/2773183/Jan.18.2019.3_57.PM.zip)

**Comment by KellyeDC-zz** [comment]
Issue resolved
