### ISSUE TITLE
Feature/ui curated experience

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#195]
_From @yfzwinnie on July 17, 2018 20:11_

This is mainly a commit for UI for curated experience and cleaning up previous curated experience code. No unit test is required at the moment. Task #214 

_Copied from original issue: Microsoft/Access2Justice/pull/251_

**Comment by aroubin** [comment]
_From @yfzwinnie on July 17, 2018 22:55_

Code reviewed with Andrew. Merging PR.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
