### ISSUE TITLE
Session storage is not working in browser for private mode

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#196]
_From @turpu-rakesh on July 18, 2018 5:55_

currently session is not getting retained for chrome browser in incognito mode on page redirection.
local storage and session storage won't work for safari browser in private window mode.

 

_Copied from original issue: Microsoft/Access2Justice#252_

**Comment by aroubin** [comment]
_From @turpu-rakesh on July 18, 2018 5:56_

#85

**Comment by yfzwinnie** [comment]
Completed as part of MVP
