### ISSUE TITLE
Changes for adding a new Business Logic method for Retrieving User data from resource collection

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#198]
_From @charmila-c on July 18, 2018 12:40_

#255 

_Copied from original issue: Microsoft/Access2Justice/pull/256_

**Comment by aroubin** [comment]
_From @charmila-c on July 19, 2018 6:58_

Added this logic in another PR and it got merged to develop. So, closing this PR

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
