### ISSUE TITLE
code analysis issues related in API code

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#199]
_From @turpu-rakesh on July 18, 2018 13:49_

Change 'Components' to be read-only by removing the property setter.	
Change 'Tags' to be read-only by removing the property setter.	
Change 'Buttons' to be read-only by removing the property setter.	
Change 'Fields' to be read-only by removing the property setter.

_Copied from original issue: Microsoft/Access2Justice#257_

**Comment by aroubin** [comment]
_From @alaatadmori on July 25, 2018 16:18_

These are not bugs. It is a false alarm of the code analyzer. When I follow the suggestion of the analyzer the solution doesn't build, because I'm assigning values to these properties, they can't be readonly. I added an exception for this code.

**Comment by yfzwinnie** [comment]
Completed as part of MVP
