### ISSUE TITLE
UI Changes for chat component and moved the forms & steps next to the…

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#2]
_From @raghunath2711 on February 8, 2018 0:23_

… chatbot.

Verbiage changes

_Copied from original issue: Microsoft/Access2Justice/pull/2_

**Comment by aroubin** [comment]
_From @msftclas on February 8, 2018 0:23_

[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/Microsoft/Access2Justice?pullRequest=2) <br/>All CLA requirements met.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
