### ISSUE TITLE
Create UI for Search Results (US#12)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#20]
_From @czdiana2321 on May 3, 2018 6:24_

_Copied from original issue: Microsoft/Access2Justice#20_

**Comment by aroubin** [comment]
_From @yfzwinnie on May 7, 2018 22:25_

Assigning this to myself since the UI for the search result page is similar to the the subtopics page within topics-resources.

**Comment by aroubin** [comment]
_From @yfzwinnie on May 22, 2018 16:50_

Moving this to resolved since this is a duplicate of #66

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
