### ISSUE TITLE
190_SearchPipeUnitTests review changes merged with Develop

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#201]
_From @venkati-naidu on July 19, 2018 6:25_

Ref: #232 - Review comments for Task#190_SearchPipeUnitTests  and merged with latest  Develop branch. Hence cancelling the #232 to avoid the confusion.
Please review and provide your comments. 

_Copied from original issue: Microsoft/Access2Justice/pull/260_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
