### ISSUE TITLE
Jasmine testcases added for pagination component

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#202]
_From @venkati-naidu on July 19, 2018 12:46_

I have done the Jasmine test cases for Pagination component. Please review and provide your comments.
Note: The task is remain open (i.e. #189 ) as I need to complete the test cases for Search service / Search Results.

_Copied from original issue: Microsoft/Access2Justice/pull/261_

**Comment by aroubin** [comment]
_From @yfzwinnie on July 19, 2018 20:14_

Code review completed. Merged PR.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
