### ISSUE TITLE
Feature/save remove resources to profile

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#204]
_From @charmila-c on July 20, 2018 12:52_

PR for tasks #221 , #222 , #213 

Merged PRs, #228, #246 

For testing, please use the plan ID: cf152275-32b2-b22c-de54-42de8fdfe778 
append in URL as:  plan/cf152275-32b2-b22c-de54-42de8fdfe778

Step 1: For testing(marking steps completed/removing an item from plan) the personalized plan page before saving to profile,
- Please update your logged in encrypted user Id generated at app.component.ts in DB for the document with above id(cf152275-32b2-b22c-de54-42de8fdfe778) in resource collection.
- Please follow below steps to get the encrypted user Id from app.component.ts
      1. Place a beak point at Line 38 in ngOnit() method
      2. On clicking Login, track the data fetched into profileData.
      3. Copy the User Id value generated in profileData and update it in DB for "oId" property of the plan 
         document with id(cf152275-32b2-b22c-de54-42de8fdfe778)
      4. By following the above steps, if the user wants to make any changes to the plan generated at the 
         end of curated experience before saving it to profile, the changes will be updated and updated 
         changes will be saved to profile.

**Note:** No need to follow the above mentioned step 1, if the user don't want to make any changes to the generated personalized plan before saving it to profile.

_Copied from original issue: Microsoft/Access2Justice/pull/264_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
