### ISSUE TITLE
Display modal that prompt user to enter location if location is not detected

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#207]
_From @yfzwinnie on July 24, 2018 1:14_

Acceptance Criteria:
- Location service should auto detect user location when they visit the website
- If location is not detected, we should display a modal that prompt user to enter location

_Copied from original issue: Microsoft/Access2Justice#267_

**Comment by KellyeDC-zz** [comment]
Issue resolved/complete
