### ISSUE TITLE
When searching for "I'm getting kicked out", it's not matched with the correct intent (eviction)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#208]
_From @yfzwinnie on July 24, 2018 1:15_

_Copied from original issue: Microsoft/Access2Justice#268_

**Comment by aroubin** [comment]
_From @turpu-rakesh on July 25, 2018 13:39_

Hi Team - We are getting below response from LUIS and top intent score is 88% but our Upper threshold score is 90% that's the reason it is fetching web resources than internal resources. So, we need train our Luis.
{
  "query": "i'm getting kicked out",
  "topScoringIntent": {
    "intent": "Tenant's rights",
    "score": 0.8879762
  },
  "intents": [
    {
      "intent": "Tenant's rights",
      "score": 0.8879762
    },
    {
      "intent": "Eviction",
      "score": 0.8877346
    }  ],
  "entities": []
}

**Comment by svasylenko** [comment]
Verified.

![image](https://user-images.githubusercontent.com/46557859/51528544-95697480-1e3f-11e9-92be-2073043bec97.png)

**Comment by KellyeDC-zz** [comment]
Issue resolved
