### ISSUE TITLE
Feature/189 units for pagination search results

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#210]
_From @venkati-naidu on July 24, 2018 14:44_

Jasmine test cases added for Search Results component. Please review and provide your comments

_Copied from original issue: Microsoft/Access2Justice/pull/271_

**Comment by aroubin** [comment]
_From @venkati-naidu on July 25, 2018 5:57_

fixed according to review comments

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
