### ISSUE TITLE
Import Resources/Topics from the 'Curated Experience Supplement' excel sheet

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#215]
_From @alaatadmori on July 25, 2018 19:11_

This task is longer valid since the personalized plan model in A2J Author changed and no longer requires an excel sheet supplement. Moving to closed and will open new tasks to work with the new A2J author model (template.json).

_Copied from original issue: Microsoft/Access2Justice#279_

**Comment by KellyeDC-zz** [comment]
Issue resolved/completed
