### ISSUE TITLE
Added schema for HomeContent, PrivacyPromiseContent and HelpAndFaqsCo…

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#220]
_From @SoniRathore on July 26, 2018 12:11_

Created model for static content of Home, Privacy Promise and Help & FAQs.

_Copied from original issue: Microsoft/Access2Justice/pull/284_

**Comment by aroubin** [comment]
_From @alaatadmori on July 26, 2018 17:27_

🥇 
Hey Soni, good job on this PR. I very much liked that you are using strongly-typed objects instead of depending on a dynamic type.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
