### ISSUE TITLE
Bing map url load issue in https

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#229]
_From @vennasr on July 30, 2018 8:48_

1) Explicitly passed the https protocol in the url. 
2) Added virtual path option to swagger in case the application is hosted in a single app service user has to provide the virtual path in the config. Default value is fine when the application is hosted in multiple web apps.
3) We need to use the following CustomConfigId "1992351710" for bing search hence updated once again.

_Copied from original issue: Microsoft/Access2Justice/pull/294_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
