### ISSUE TITLE
Curated experience business logic (US#15)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#23]
_From @czdiana2321 on May 3, 2018 6:29_

_Copied from original issue: Microsoft/Access2Justice#24_

**Comment by aroubin** [comment]
_From @alaatadmori on July 14, 2018 5:34_

This PR contains the V1 of the curated experience. It has the code to convert A2J Author schema to a Curated Experience schema, and it has all what the UI needs to 'play' the Curated Experience on screen. The next step will be to convert A2J Author 'logic' to a compatible logic in our system.
Code reviewed with Andrew.

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
