### ISSUE TITLE
ResourceTypeFilter 'video' is generated in additional to 'videos' when navigating from Subtopic Detail Page

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#232]
_From @yfzwinnie on July 30, 2018 22:7_

![image](https://user-images.githubusercontent.com/20545930/43426353-4448c41c-940a-11e8-98dc-2fc0932c06e0.png)

Steps to reproduce:
1. Navigate to http://localhost:5150/topics/3e278591-ec50-479d-8e38-ae9a9d4cabd9
2. Click on see more videos

_Copied from original issue: Microsoft/Access2Justice#297_

**Comment by aroubin** [comment]
_From @yfzwinnie on August 8, 2018 20:35_

This issue has been resolved after we migrated to the new database.

**Comment by KellyeDC-zz** [comment]
Issue resolved
