### ISSUE TITLE
Feature/302 resolve test case issue

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#234]
_From @venkati-naidu on August 1, 2018 13:51_

Issues fixed in the spec files like routing issues etc. Profile,UpperNavComponent,RemoveButtonComponent,SaveButtonComponent,ShareButtonComponent, SearchComponent, GuidedAssistantSidebarComponent,TopicsResourceComponent

Please review and provide your comments.

_Copied from original issue: Microsoft/Access2Justice/pull/303_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
