### ISSUE TITLE
Feature/error page

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#235]
_From @vennasr on August 2, 2018 5:50_

Implemented 404 redirect. Added HTTP interceptor to handle all the errors at one place, if we need to handle any specific error and redirects we can handle in this file.

_Copied from original issue: Microsoft/Access2Justice/pull/305_

**Comment by aroubin** [comment]
_From @alaatadmori on August 5, 2018 4:36_

 Hi Sateesh, can you please pull latest from develop (many changes are there!) and merge this conflict and push again? Thank you.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
