### ISSUE TITLE
Feature/301 parent topic id fix

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#239]
_From @xilin95 on August 2, 2018 23:56_

_Copied from original issue: Microsoft/Access2Justice/pull/311_

**Comment by aroubin** [comment]
_From @alaatadmori on August 2, 2018 23:57_

🥇 Good job on your first bug fix!!

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
