### ISSUE TITLE
Feature/display static resource navigation

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#240]
_From @venkati-naidu on August 3, 2018 13:48_

Merged the below Tasks in the this PR. Please review and provide your comments.

Display help & faq's content from backend storage #288 
Display privacy promise content from backend storage #285 
Display home content from backend storage #289

_Copied from original issue: Microsoft/Access2Justice/pull/315_

**Comment by aroubin** [comment]
_From @yfzwinnie on August 7, 2018 20:38_

Venkati, I'm still seeing alot of errors in the devTools. Can you see if you are getting these errors as well? These are likely errors due to the fact that certain properties might not be loaded by the time the page loads so we're getting a "Cannot read property of undefined". We need to check that these properties exist in the html code using *ngIf or using the safe navigation operator ( ?. ) https://angular.io/guide/template-syntax#the-safe-navigation-operator----and-null-property-paths

Also, I'm not seeing any content in the help & FAQs page. Please test all pages and ensure we have error free and all contents are loading correctly. 

![image](https://user-images.githubusercontent.com/20545930/43801107-ffbaf692-9a46-11e8-8dc3-6688760d69ff.png)

One more comment, when I change location, I am not seeing the image change. Is this part of this PR or a separate PR? Thanks.

**Comment by aroubin** [comment]
_From @venkati-naidu on August 8, 2018 13:24_

Hi Winnie, the similar image is placed for Hawaii and Alaska and that is the reason for displaying the same image for both locations. Below is the reference: https://cs4892808efec24x447cx944.blob.core.windows.net/static-resource/alaska/assets/images/primary-illustrations/hawaii.svg
https://cs4892808efec24x447cx944.blob.core.windows.net/static-resource/hawaii/assets/images/primary-illustrations/hawaii.svg

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
