### ISSUE TITLE
Feature/Perma link  - Implemented Backend logic

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#241]
_From @vennasr on August 3, 2018 15:53_

Implemented Backend logic for Share and Unshare. Please review the code and let me know if any issues.
During share we need the actual routeUrl to redirect back to the same page when user navigates to the site through permalink. As we are already passing the resourceId, expecting to pass only the routeurl like(plan|topics|subtopics|profile|resource). Even we can pass the complete absoluteUrl from client side, in that case we need to pass the url value directly. 

_Copied from original issue: Microsoft/Access2Justice/pull/316_

**Comment by aroubin** [comment]
_From @alaatadmori on August 4, 2018 18:38_

Hi Sateesh, thanks for your work. I merged the code but I didn't delete the branch because we still need 2 additional things to call the feature complete:
1. you are using SHA256 which is good, I'm thinking instead of returning the entire hash let's just return the first 7 characters of it (so we will store the full hash in the profile but to make the permalink more friendly to the user we will only return the first 7 characters). When a user paste the permalink in the browser, we will compare the first 7 characters of the hash and return the url if there is a match. (I think this is similar to what bitly does?!). Seven characters are reasonably enough to ensure uniqueness across all the permalinks we will store in the users profiles.
2. we need to add couple of unit tests. This is not urgent as we have a lot to finish on Monday but please keep it on your radar and implement it when you have a room for some additional work (maybe after Tuesday's demo!).

Please let me know if you have questions. Thanks!

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
