### ISSUE TITLE
Added endpoint to get resource by resource id

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#242]
_From @xilin95 on August 3, 2018 17:27_

_Copied from original issue: Microsoft/Access2Justice/pull/317_

**Comment by aroubin** [comment]
_From @msftclas on August 3, 2018 17:27_

[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/Microsoft/Access2Justice?pullRequest=317) <br/>All CLA requirements met.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
