### ISSUE TITLE
Navigating directly to http://localhost:5150/profile does not prompt the user to login, it should.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#247]
_From @alaatadmori on August 5, 2018 5:44_

If I paste this in the browser: http://localhost:5150/profile I don't get prompted to login, instead I see an empty profile page. Navigating to profile should direct me to login page if I'm not already logged in.

_Copied from original issue: Microsoft/Access2Justice#322_

**Comment by aroubin** [comment]
_From @vennasr on August 19, 2018 19:17_

#386

**Comment by svasylenko** [comment]
[247.zip](https://github.com/LSCOIT/LegalNavigator/files/2782272/247.zip)

Verified.

**Comment by KellyeDC-zz** [comment]
Issue resolved
