### ISSUE TITLE
Updated static contents API to fetch data based on page pame and loca…

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#249]
_From @SoniRathore on August 6, 2018 10:56_

Updated static content API for below changes.
1. changed document id from name to guid.
2. fetch contents based on page name and location.
3. updated upsert methods for above changes. 

_Copied from original issue: Microsoft/Access2Justice/pull/326_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
