### ISSUE TITLE
Feature/266 link see more organizations on topics subtopics search results page

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#250]
_From @durga-rajasekhar on August 6, 2018 13:6_

Pull Request for the following functionalities:
1) Click for  "See More Organizations " from right side bar of  topics landing page.
2) Click for  "See More Organizations " from right side bar of subtopics page.
3) Click for  "See More Organizations " from right side bar of subtopic-details page.
4) Click for  "See More Organizations " from  right side bar of search-result page.

Note:Jasmine test cases are not updated as per the new methods added in the components,and
currently we haven't implemented see more Organizations button click navigation to search page from resource type(Articles, Videos) pages. Since we need to check with Product Owner on multiple scenario's.

_Copied from original issue: Microsoft/Access2Justice/pull/327_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
