### ISSUE TITLE
made swagger the landing page of the api

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#257]
_From @xilin95 on August 8, 2018 18:46_

_Copied from original issue: Microsoft/Access2Justice/pull/337_

**Comment by aroubin** [comment]
_From @alaatadmori on August 8, 2018 21:20_

I needed to revert this commit because it was causing a routing error. I moved the relevant task to the backlog again.

**Comment by KellyeDC-zz** [comment]
@svasylenko Confirm that this issue is resolved.

**Comment by KellyeDC-zz** [comment]
Issue resolved
