### ISSUE TITLE
Create control for homepage to list topics (US#14)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#26]
_From @czdiana2321 on May 3, 2018 6:33_

_Copied from original issue: Microsoft/Access2Justice#27_

**Comment by aroubin** [comment]
_From @yfzwinnie on May 22, 2018 16:48_

We are still waiting for decision on this from Fellswoop and stakeholders on the sequence of topics on the homepage. Moving this to to do for later once we have the decision.

**Comment by aroubin** [comment]
_From @yfzwinnie on June 6, 2018 1:3_

Code review with Andrew and Alaa. Moving this to resolve.

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
