### ISSUE TITLE
Feature/331_search page refresh load task

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#261]
_From @turpu-rakesh on August 9, 2018 13:47_

#331 

_Copied from original issue: Microsoft/Access2Justice/pull/344_

**Comment by aroubin** [comment]
_From @turpu-rakesh on August 9, 2018 15:56_

1. Fixed Reverse issue while displaying the Resource Type Tabs in Search page.
2. Location filter in search results page was updating to global location and it was not retaining to local location.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
