### ISSUE TITLE
Create backend service (US#14)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#27]
_From @czdiana2321 on May 3, 2018 6:33_

_Copied from original issue: Microsoft/Access2Justice#28_

**Comment by aroubin** [comment]
_From @durga-rajasekhar on May 3, 2018 12:3_

Started working on this task and assigning it to my name.

**Comment by aroubin** [comment]
_From @durga-rajasekhar on May 29, 2018 3:23_

Acceptance Criteria:
1)should create sample data for topics, subtopics and subtopic details in document db
2)create endpoint uri to display topics
3)create endpoint uri to display subtopics
4)create endpoint uri to display subtopic details
5)create unit test cases for endpoint uri methods

**Comment by aroubin** [comment]
_From @yfzwinnie on June 6, 2018 4:20_

Code review with Alaa and Andrew. Moving to Resolve.

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
