### ISSUE TITLE
Static resource api request is returning internal server error when location is not defined.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#273]
_From @yfzwinnie on August 13, 2018 20:6_

Prior to user allowing or denying location detection, we are getting 500 internal server errors because location has not been defined. We need to change the logic where if no location is given, front end should receive the default display until location changes.

![image](https://user-images.githubusercontent.com/20545930/44055331-f4149b60-9ef9-11e8-80a6-95b6133a3bda.png)
![image](https://user-images.githubusercontent.com/20545930/44055340-fb47a21a-9ef9-11e8-8401-b6b5583989bc.png)
![image](https://user-images.githubusercontent.com/20545930/44055423-2f9d1cc0-9efa-11e8-8d3e-c8f8c5fb5b33.png)

_Copied from original issue: Microsoft/Access2Justice#359_

**Comment by yfzwinnie** [comment]
Completed as part of MVP
