### ISSUE TITLE
Feature/refactor api call for static contents

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#277]
_From @SoniRathore on August 14, 2018 10:0_

Code changes done to reduce static contents API calls for below components for task #356.
- home
- upper-nav
- lower-nav
- about
- help & faq
- privacy
- map
- language
- footer

_Copied from original issue: Microsoft/Access2Justice/pull/363_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
