### ISSUE TITLE
Create ability to fetch intents from LUIS (US#12)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#28]
_From @czdiana2321 on May 3, 2018 6:36_

Create ability to fetch intents from LUIS and Implement Unit Test cases.

_Copied from original issue: Microsoft/Access2Justice#30_

**Comment by aroubin** [comment]
_From @turpu-rakesh on May 3, 2018 9:58_

Started working on this task and assigning it to my name.

**Comment by aroubin** [comment]
_From @alaatadmori on May 22, 2018 16:56_

Moving this to resolved as it is a duplicate of task #61.

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
