### ISSUE TITLE
Feature/349 display default dynamic content

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#289]
_From @durga-rajasekhar on August 16, 2018 14:0_

Hi Alaa, this pull request is for API part of this task(349 display default dynamic content), earlier we have considered only Id's for getting topics,subtopics,and subtopic details as well as resources data ,now we are getting these data by  location also.
-Implemented API unit test cases for new method added in CosmosDbDynamicQueries.cs file.
please provide your review comments if everything fine, i will start work on UI part of this task.
Thanks,
Rajasekhar.

_Copied from original issue: Microsoft/Access2Justice/pull/376_

**Comment by aroubin** [comment]
_From @alaatadmori on August 16, 2018 17:39_

👍 Good job on this PR!

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
