### ISSUE TITLE
Create resource storage (US#12)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#29]
_From @czdiana2321 on May 3, 2018 6:37_

Task Description:

- Create actual schema - Creation of backend schema
- Persist actual schema - Creation of backend service
- CRUD interface from manage code – 
	1. Script creation to seed Topic and Resources data for development purpose. Execute this script so that every time we rebuild database, topics and resources data is populated.
	2. Using this script create few topics and resources and link resources to topics.
        Note: UI creation there will be separate user story in upcoming sprints.
- Create API End point

_Copied from original issue: Microsoft/Access2Justice#31_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
