### ISSUE TITLE
Feature/save resource in user profile

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#293]
_From @charmila-c on August 17, 2018 15:14_

#343 

#345 

_Copied from original issue: Microsoft/Access2Justice/pull/380_

**Comment by aroubin** [comment]
_From @charmila-c on August 21, 2018 13:12_

Merged develop and resolved conflicts

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
