### ISSUE TITLE
Need to adjust location filter for search

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#296]
_From @yfzwinnie on August 18, 2018 0:11_

Currently when filtering location, we are passing the state, locality, zip code, county (everything returned by Bing Map) for the api request. We should only send the filter parameter user entered. For example, if they filter by the zip code, we only need to set the zip code as the location filter parameter.

_Copied from original issue: Microsoft/Access2Justice#383_

**Comment by aroubin** [comment]
_From @vennasr on August 20, 2018 14:53_

#389

**Comment by yfzwinnie** [comment]
Completed as part of MVP
