### ISSUE TITLE
Incorporated metadata changes like : StateDeviation, Outcome and Stat…

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#3]
_From @WLH-Gedion on February 9, 2018 1:27_

…e. Renamed the Database name from "AL" to "AK" , and modified the lowconfidence intent bag

_Copied from original issue: Microsoft/Access2Justice/pull/3_

**Comment by aroubin** [comment]
_From @msftclas on February 9, 2018 1:27_

[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/Microsoft/Access2Justice?pullRequest=3) <br/>All CLA requirements met.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
