### ISSUE TITLE
Feature/userstory 12

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#30]
_From @turpu-rakesh on May 3, 2018 11:41_

Hello, 

Created skeleton for LUIS Search, added swagger,injected configuration and enabled Application Insights. please review the changes and merge.

Thanks,
Rakesh

_Copied from original issue: Microsoft/Access2Justice/pull/33_

**Comment by aroubin** [comment]
_From @msftclas on May 3, 2018 11:41_

[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/Microsoft/Access2Justice?pullRequest=33) <br/>All CLA requirements met.

**Comment by aroubin** [comment]
_From @alaatadmori on May 3, 2018 20:38_

Hi Rakesh, thanks for the good work. Can you please make the PR against the 'develop' branch, it is currently set to be merged into the 'master' branch. Thanks.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
