### ISSUE TITLE
Bug 383 Fixed - Need to adjust location filter for search

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#302]
_From @vennasr on August 20, 2018 14:53_

When user selected zip code in location filter in search screen passing State and Zip code to get the results. Sometimes the same Zip code(96741) is available in another Country hence explicitly passing State along with Zip code to fetch proper results. 

_Copied from original issue: Microsoft/Access2Justice/pull/389_

**Comment by aroubin** [comment]
_From @vennasr on August 21, 2018 7:31_

Added condition for all the scenarios like State|City|County|Zipcode. Passing only the  required selection like only zipcode when user searched for zipcode

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
