### ISSUE TITLE
Navigating to /profile route, still seeing an empty profile page prior to redirecting to login page.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#303]
_From @yfzwinnie on August 20, 2018 16:23_

Seeing this screen prior to redirecting to login 

![image](https://user-images.githubusercontent.com/20545930/44353110-e8876780-a45a-11e8-9ca7-686ae91aa063.png)

_Copied from original issue: Microsoft/Access2Justice#390_

**Comment by aroubin** [comment]
_From @yfzwinnie on September 11, 2018 0:41_

Need to implement Route Guard to check if user profile data is defined before routing to /profile.

https://angular.io/guide/router#guards

**Comment by aroubin** [comment]
_From @turpu-rakesh on October 15, 2018 5:32_

This issue will get fixed, after implementing RBAC at UI.

**Comment by svasylenko** [comment]
[303.zip](https://github.com/LSCOIT/LegalNavigator/files/2779137/303.zip)

Verified.

**Comment by KellyeDC-zz** [comment]
Confirmed resolved
