### ISSUE TITLE
User location, user id, and user name are stored in session storage when accessing the shared permalink

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#304]
_From @yfzwinnie on August 20, 2018 16:41_

![image](https://user-images.githubusercontent.com/20545930/44353908-42892c80-a45d-11e8-903d-e130485603c7.png)
![image](https://user-images.githubusercontent.com/20545930/44360648-4d00f180-a470-11e8-8135-d049135a9ab6.png)

![image](https://user-images.githubusercontent.com/20545930/44360601-2cd13280-a470-11e8-9dd0-c726eabece9b.png)

When I navigate to one of the resource saved (http://localhost:5150/resource/2fe9f117-bfb5-469f-b80c-877640a29f75), the web app is bringing up resources for Alaska.

![image](https://user-images.githubusercontent.com/20545930/44353979-71070780-a45d-11e8-9d19-49b847c4a542.png)

Because my user id and name are stored in session storage, I can also save resources to the profile of the person who shared the resources with me without login in. 
![image](https://user-images.githubusercontent.com/20545930/44354152-e1ae2400-a45d-11e8-86ef-e0686eb0e6aa.png)

_Copied from original issue: Microsoft/Access2Justice#392_

**Comment by aroubin** [comment]
_From @vennasr on August 22, 2018 14:23_

1) Complete user details are coming from the personalization service. Now the implementation got changed and the issue is resolved now.
2) Alaska related Organization data is mapped to Hawaii that is the reason the data is populating. Data issue.
3) Save resource issue will resolve with this PR #431

**Comment by svasylenko** [comment]
to be fixed after fixing saving to My Plan feature
