### ISSUE TITLE
Feature/231 print plan

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#306]
_From @SoniRathore on August 21, 2018 12:31_

Implemented print functionality for following pages. #231 
-Subtopic-detail
-Personalized-Plan
-Article
-Organizations
-My Plan
-My Saved Resources

_Copied from original issue: Microsoft/Access2Justice/pull/395_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
