### ISSUE TITLE
Feature/jasmine test cases actionplan

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#307]
_From @durga-rajasekhar on August 21, 2018 14:30_

I have fixed the failed jasmine test cases in action plan component and
Removed un-used files(organization.ts,home.service.ts,home.service.spec.ts)
Please review and advice if any concerns.

_Copied from original issue: Microsoft/Access2Justice/pull/396_

**Comment by aroubin** [comment]
_From @yfzwinnie on August 25, 2018 16:24_

Charmila, some of the test are still failing for action plan. Please make sure the test are passing.

**Comment by aroubin** [comment]
_From @charmila-c on August 28, 2018 9:24_

Fixed Unit test cases for action-plans.component.ts, personalized-plan.component.ts and personalized-plan.service.ts

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
