### ISSUE TITLE
Search result location filtering is returning 400 when search for a location that doesn’t exist

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#309]
_From @yfzwinnie on August 21, 2018 23:54_

![image](https://user-images.githubusercontent.com/20545930/44435002-e4467180-a562-11e8-86cd-4d13eb2d209a.png)

![image](https://user-images.githubusercontent.com/20545930/44435007-e90b2580-a562-11e8-9fdc-84a99a3f90b1.png)

![image](https://user-images.githubusercontent.com/20545930/44435013-ec9eac80-a562-11e8-835f-651131a39d31.png)

_Copied from original issue: Microsoft/Access2Justice#399_

**Comment by aroubin** [comment]
_From @yfzwinnie on August 22, 2018 0:1_

Looks like this might be resolved with PR #389

**Comment by svasylenko** [comment]
400 error does not appear anymore but other bug found.

![image](https://user-images.githubusercontent.com/46557859/51478942-87f7b000-1d95-11e9-8b82-23306de80771.png)

**Comment by yfzwinnie** [comment]
This is related to partitioning and @alaatadmori is working on fixing this. In the meantime, you can search in Hawaii to see the filtering and sorting: 

![image](https://user-images.githubusercontent.com/20545930/51482212-d5f3c000-1d63-11e9-92b4-ba99b11d27cd.png)

**Comment by svasylenko** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/46557859/52411856-c86d6280-2ae5-11e9-9611-074ea6326d1c.png)
