### ISSUE TITLE
Enable swagger (US#12)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#31]
_From @turpu-rakesh on May 3, 2018 15:1_

Implement swagger UI for API testing.
Enable Application Insights for default logging for API project.

_Copied from original issue: Microsoft/Access2Justice#35_

**Comment by aroubin** [comment]
_From @alaatadmori on May 23, 2018 23:53_

I pulled the breach and reviewed it.

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
