### ISSUE TITLE
Added changes to show complete url and display application name and u…

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#310]
_From @SoniRathore on August 22, 2018 11:19_

Following updates are done as part of this PR. #410 

1. Updated URLs for printing.
2. displaying application name and url dynamically.
3. Updated to show complete url for external links while printing.
4. Added print functionality for shared contents.

To do-
Completed checkbox need to be printed checked when its checked in UI.

_Copied from original issue: Microsoft/Access2Justice/pull/400_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
