### ISSUE TITLE
fix for bugs 398, 391, 407

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#311]
_From @charmila-c on August 22, 2018 12:38_

#391 #398 

_Copied from original issue: Microsoft/Access2Justice/pull/401_

**Comment by aroubin** [comment]
_From @charmila-c on August 23, 2018 9:46_

#407 has been covered as part of this PR

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
