### ISSUE TITLE
Fixed bug 392 - Removed local session storage for user details

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#313]
_From @vennasr on August 22, 2018 14:16_

Removed session storage functionality for user details and moved to global service hence the changes are in multiple places.  
As we have implemented topics to display based on location but during share we should not consider location hence updated the code to show topics.

Please review the implementation approach and if there any changes let me know.

_Copied from original issue: Microsoft/Access2Justice/pull/403_

**Comment by aroubin** [comment]
_From @yfzwinnie on August 27, 2018 17:45_

It looks like we might've broken some of the functionalities with this PR. 
1. I can't save topics and resources to my profile now. Getting a 500 error. 
![image](https://user-images.githubusercontent.com/20545930/44675511-9a87dc00-a9e5-11e8-9b4b-32ffd7c07bc5.png)

2. When I share my profile, I don't see the saved resources

My view when I'm logged in:
![image](https://user-images.githubusercontent.com/20545930/44675556-be4b2200-a9e5-11e8-8351-e1c07984159b.png)

Shared view:
![image](https://user-images.githubusercontent.com/20545930/44675572-cb681100-a9e5-11e8-91cd-2fece9d6ace3.png)

3. Not able to see the service-org sidebar again until I change my location
![image](https://user-images.githubusercontent.com/20545930/44675791-51845780-a9e6-11e8-8077-0d6b871820b3.png)

4. If I refresh the page, my login information is gone and I have to login again.

**Comment by aroubin** [comment]
_From @vennasr on August 31, 2018 15:35_

This branch is outdated hence closing this and will raise a new PR for the same bug fix.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
