### ISSUE TITLE
Evolve data import tools for topics and resources

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#316]
_From @aroubin on August 23, 2018 4:46_

- import contents of Excel sheet
- perform basic validation of content 
- Invoke APIs to create topics / resources. 

Sample data files: https://teams.microsoft.com/_#/files/Architecture%20and%20Technical%20Design?threadId=19%3A621cf4a906984eadb12c936353194e0d%40thread.skype&ctx=channel&context=Data%2520Import%2520Templates

_Copied from original issue: Microsoft/Access2Justice#406_

**Comment by yfzwinnie** [comment]
Completed as part of MVP

**Comment by KellyeDC-zz** [comment]
Resolved/completed
