### ISSUE TITLE
Feature/multiple domain login issue

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#319]
_From @vennasr on August 23, 2018 12:39_

Removed authentication from api level and added at web app level. Created separate client id and secrets for the new web app redirection and pushed as part of the changes.

I have updated the web app path for the dev server in the existing app registration. Please review the approach and let me know if any issues

_Copied from original issue: Microsoft/Access2Justice/pull/411_

**Comment by aroubin** [comment]
_From @alaatadmori on August 23, 2018 20:40_

The code looks good to me. I added @aroubin too to advice on the general direction.

**Comment by aroubin** [comment]
Thank you, but I think we need to have additional discussions on how the APIs will be secured. If we use API keys, we can't just embed them in client side code. Next week, let us revisit this topic and evaluate if we should have service proxies as part of the web app that call APIs with API keys.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
