### ISSUE TITLE
Create Cosmos DB CRUD operations (US#13)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#32]
_From @alaatadmori on May 3, 2018 19:57_

_Copied from original issue: Microsoft/Access2Justice#37_

**Comment by aroubin** [comment]
_From @alaatadmori on May 3, 2018 19:58_

Create the basic CRUD operations of the Cosmos DB #23

**Comment by aroubin** [comment]
_From @alaatadmori on May 16, 2018 7:49_

Code reviewed with Andrew.

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
