### ISSUE TITLE
Import A2J Author Personalized Plan and parse logical IF statements with boolean values

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#321]
_From @alaatadmori on August 24, 2018 17:54_

This task is the successor of task #279 "Import Resources/Topics from the 'Curated Experience Supplement' excel sheet".

_Copied from original issue: Microsoft/Access2Justice#414_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
