### ISSUE TITLE
Urls are showing in mobile version after implementing print feature

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#323]
_From @yfzwinnie on August 27, 2018 18:50_

Need to not use web-hidden class since it shows the urls when in mobile view

![image](https://user-images.githubusercontent.com/20545930/44679313-7b8e4780-a9ef-11e8-98ec-47b258f541a7.png)

_Copied from original issue: Microsoft/Access2Justice#418_

**Comment by yfzwinnie** [comment]
Completed as part of MVP
