### ISSUE TITLE
Need to implement "Start The Guided Assistant" link of subtopics page side bar component to navigate the results in curated experience page 

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#328]
_From @durga-rajasekhar on August 28, 2018 13:35_

_Copied from original issue: Microsoft/Access2Justice#423_

**Comment by yfzwinnie** [comment]
This was completed as part of the MVP

**Comment by KellyeDC-zz** [comment]
@svasylenko Where is this in the UI?

**Comment by grawdon** [comment]
This option is now available from the Topics pages, but I asked Glorium to only make it visible when there is actually a Guided Assist for a topic. That hasn't been done yet.

**Comment by grawdon** [comment]
@KellyeDC We wanted to move this above the map. Should it be part of this issue or should we start a new issue?
