### ISSUE TITLE
Support for Advanced A2JAuthor Logic

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#344]
_From @aroubin on September 6, 2018 4:32_

Support for A2JAuthor advanced functionality such as loops, GOTOs, etc..

_Copied from original issue: Microsoft/Access2Justice#441_

**Comment by aroubin** [comment]
_From @amitabhm21 on December 7, 2018 23:22_

The platform will not replicate the A2J author viewer. The scenarios for Legal Assist dont require these constructs and we will not implement and complicate the A2j Autor Adaptor

**Comment by yfzwinnie** [comment]
Closed by Amitabh
