### ISSUE TITLE
Ability to unshare a personalized plan

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#346]
_From @aroubin on September 6, 2018 4:36_

_Copied from original issue: Microsoft/Access2Justice#443_

**Comment by breeglej** [comment]
@KellyeDC  - Need to make share work before we work on an un-share feature.

**Comment by KellyeDC-zz** [comment]
#77 Related to this feature.

**Comment by konstantin-orekhov** [comment]
07/29 - 8h

**Comment by grawdon** [comment]
@KellyeDC @yevhenobertas @asaperski-gloriumtech I tried to share from one of my accounts to another but the link never showed up, so I couldn't test to see if I could remove it. Does this do in batches or real time?
