### ISSUE TITLE
Implement save functionality to save guided assistant progress

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#350]
_From @yfzwinnie on September 6, 2018 18:12_

Acceptance criteria:
- user progress should be save **automatically** as they go through the guided assistant
- if user closes the browser or the tab, prompt user to save progress to profile.
- redirects user to login/sign up page
- save progress to user account
- user should be able to continue their progress the next time they login

_Copied from original issue: Microsoft/Access2Justice#447_

**Comment by svasylenko** [comment]
related task #351

**Comment by KellyeDC-zz** [comment]
@grawdon Is this a high priority?

**Comment by KellyeDC-zz** [comment]
Ready for PO Review in DEV.

**Comment by grawdon** [comment]
@KellyeDC I did not see an options to save as I went through the interview or upon leaving the tab or browser. Am I missing something?

**Comment by KellyeDC-zz** [comment]
@grawdon It appears to save along the way without notifying the user.  The save function (in UI) is only at the end of the interview.  We would need to add a new user story to allow the user to save along the way.  My concern is that the user may not in most cases and the platform should save for the user.  Let me know your thoughts.
