### ISSUE TITLE
As Portal User, I want to be directed to the correct curated experience so that I can build a plan of action. 

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#36]
_From @czdiana2321 on May 7, 2018 19:22_

USER->UI
Acceptance Criteria:
1. Portal User is directed to the correct curated experience from search results (based on my search query). E.g. searching for Eviction will allow user to see a curated experience for Eviction if there is one.
2. Portal User is able to start building the action plan.
3. Alternatively, curated experience can be entered from the topic page. 

#224 
#195 
#194 

_Copied from original issue: Microsoft/Access2Justice#43_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh
