### ISSUE TITLE
State level topics are not displayed for associated city/county.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#364]
_From @turpu-rakesh on September 14, 2018 4:39_

State level topics are not displayed for associated city/county. 

If we select Anchorage city then topics are not being displayed even though topics are available for Alaska. 

_Copied from original issue: Microsoft/Access2Justice#461_

**Comment by aroubin** [comment]
_From @vennasr on October 15, 2018 10:38_

@aroubin @turpu-rakesh  @yfzwinnie  - To fix this we need to update the location related query but do we need to handle this at client side or at the backend.  Please confirm.
ClientSide - If the requirement is to show only State level then will pass only State to the query so that the issue will resolve. 
Backend - We need to change the location query logic so that the issue will resolve but the request charge will be around 17.95 RUs for each request.

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh
