### ISSUE TITLE
Breadcrumb should be routed to home node while switching states

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#368]
_From @venkati-naidu on September 17, 2018 7:1_

There is no change while switching from Hawaii to Alaska and vice versa while in  child notes (Breadcrumb)
Repro:
   a. Change the location to Alaska
   b. Navigate to topics
   c. Change the location to Hawaii
   d. We could see no change in the Breadcrumb
Expected: Should navigate to “All Topics" (i.e. root node

_Copied from original issue: Microsoft/Access2Justice#466_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
