### ISSUE TITLE
As Portal User, I want to view useful tips pertaining to my situation as I am working on building my action plan, so that I can better understand my rights. 

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#37]
_From @czdiana2321 on May 7, 2018 19:23_

USER->UI

Acceptance Criteria:
1. Portal User is able to view useful information as tips pertaining to user's situation.

_Copied from original issue: Microsoft/Access2Justice#44_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh
