### ISSUE TITLE
Location services is turned on, A2J site does not pick up.  

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#378]
_From @shandang on September 17, 2018 21:46_

Initial entry into A2J site: Browser message appears "A2jdevweb.azurewebsites.net wants to use your location, but first you need to go to setting and turn on location."  I already have location services turned on, but the site isn't picking it up.  

_Copied from original issue: Microsoft/Access2Justice#477_

**Comment by aroubin** [comment]
_From @yfzwinnie on September 18, 2018 18:20_

In order to allow location detection for Edge, we need to specifically set it on the settings menu. Once you've turned location detection on for Edge, open a new window and you should now get the pop up asking you if you allow location detection.

![image](https://user-images.githubusercontent.com/20545930/45707825-c0138b80-bb34-11e8-8ae2-0e9359137492.png)

**Comment by aroubin** [comment]
Not a bug

**Comment by svasylenko** [comment]
![image](https://user-images.githubusercontent.com/46557859/51392693-82545d00-1b3e-11e9-9e1c-0b28861fa54f.png)

![image](https://user-images.githubusercontent.com/46557859/51392714-90a27900-1b3e-11e9-90ce-8dcfad2486a6.png)

@KellyeDC please set a priority for fixing.

**Comment by yfzwinnie** [comment]
Completed during MVP and closed by Andrew
