### ISSUE TITLE
Breadcrumb should work when parentTopicId is null for topic

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#382]
_From @SoniRathore on September 19, 2018 14:36_

Currently breadcrumb is working when parentTopicId is empty array. It should work for null parentTopicId as well.

_Copied from original issue: Microsoft/Access2Justice#484_

**Comment by aroubin** [comment]
Correct, parent topic id will be empty for top level topics

**Comment by aroubin** [comment]
_From @SoniRathore on September 24, 2018 9:53_

Updated stored proc is available in dev cosmos db.

**Comment by KellyeDC-zz** [comment]
@grawdon Breadcrumbs issues were submitted by the states.  Please review for expected behavior.

**Comment by grawdon** [comment]
@KellyeDC I tested several topics and the breadcrumbs worked for them all. It looked resolved to me.
