### ISSUE TITLE
save articles/organizations to profile from resource page

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#387]
_From @durga-rajasekhar on September 21, 2018 12:40_

Hi Winnie,the issue(#468)is not replicating every time, and at the same time I found new issue whenever user wants to save article/organizations from (
http://localhost:5150/resource/2cb89c44-f989-42ea-b038-419e5006e8ff) to Profile, it is always Showing  "resource already added to profile" but it is not available in "MySavedResources" Tab' ,so I resolved the issue now we are able to see in 'MySavedResources'.

![capture](https://user-images.githubusercontent.com/38064880/45878211-e566fa80-bdbd-11e8-93ff-7fdbeeb0ce22.PNG)

_Copied from original issue: Microsoft/Access2Justice/pull/492_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
