### ISSUE TITLE
Refactor API route names to be more consistent

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#388]
_From @aroubin on September 21, 2018 23:0_

api routes need to use consistent naming conventions, for example, currently we have PascalCasing and lowercase variants. Let us stick with lowercase throughout. https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design

_Copied from original issue: Microsoft/Access2Justice#494_

**Comment by aroubin** [comment]
_From @alaatadmori on October 2, 2018 17:53_

Hey Andrew, what should we do in the case of a route that has more than one word to it? Should we lowercase it like this: 
curatedexperience
or curatedExperience
or curated-experience

I looked at some examples in the github website for how they name the routes, check this out:
https://help.github.com/categories/setting-up-and-managing-your-github-profile/

**Comment by aroubin** [comment]
_From @yfzwinnie on October 4, 2018 18:58_

It looks like using a dash to separate the url with more than one word is best practice according to:
https://restfulapi.net/resource-naming/

![image](https://user-images.githubusercontent.com/20545930/46496336-a5941000-c7cc-11e8-8859-c519e5decc24.png)

**Comment by aroubin** [comment]
_From @alaatadmori on October 4, 2018 22:18_

Awesome! Sounds like a plan!

p.s. I just realized that it might have been confusing when I sent that link in my previous comment, I didn't mean that you visit the page to learn about github profile stuff, I just meant to look at the URL itself to see how github names their URLs :| Sorry if I caused any confusion :|

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
