### ISSUE TITLE
Refactor API route names to be in lower case.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#412]
_From @SoniRathore on September 25, 2018 10:25_

Fixed #494 

_Copied from original issue: Microsoft/Access2Justice/pull/519_

**Comment by aroubin** [comment]
_From @SoniRathore on October 10, 2018 11:11_

Hi Winnie, 

In api.ts file, below variable (updatePlanUrl) in not used anywhere and also I dint find api upsert-user-plan. 
updatePlanUrl: userProfile + "/upsert-user-plan",

Should we remove this part from code?

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
