### ISSUE TITLE
Refactor get topics api calls

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#413]
_From @durga-rajasekhar on September 25, 2018 13:24_

#457 
Hi Winnie,
Restricted multiple API calls from the topics page, guided assistant page, and home page.
now we are  making single API call  on location change.

_Copied from original issue: Microsoft/Access2Justice/pull/520_

**Comment by aroubin** [comment]
_From @yfzwinnie on October 4, 2018 18:51_

- When I'm changing states from Alaska to Washington, the topics did not update.

![image](https://user-images.githubusercontent.com/20545930/46495873-69ac7b00-c7cb-11e8-8007-9c2d4a84c6f5.png)


- If we click "allow" when we first enter the page, it looks like we are still making alot of calls:
![image](https://user-images.githubusercontent.com/20545930/46496023-cad44e80-c7cb-11e8-8e1f-b62767668e25.png)

![image](https://user-images.githubusercontent.com/20545930/46495984-b85a1500-c7cb-11e8-8aed-ff7491f85c7d.png)

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
