### ISSUE TITLE
Need to handle invalid location search/handle invalid location error.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#414]
_From @yfzwinnie on September 26, 2018 20:45_

Currently we are only console.logging the error when a user enters an invalid location. We need to display some kind of error message to user such as "Please enter a valid location". 

On the initial location modal where a location is require, we need to not call the static resource api until a valid location has been entered.

To repro this error, enter "a" into the input location box:
![image](https://user-images.githubusercontent.com/20545930/46108516-19ae3280-c193-11e8-9fa6-cd6dda764a12.png)

_Copied from original issue: Microsoft/Access2Justice#522_

**Comment by aroubin** [comment]
_From @durga-rajasekhar on October 15, 2018 11:43_

Winnie fixed this bug.

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
