### ISSUE TITLE
Upgrade to Bootstrap 4.1.2

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#415]
_From @yfzwinnie on September 26, 2018 20:52_

Due to XSS vulnerability in Bootstrap versions 4.1.2 and under, we need to upgrade Bootstrap. 

_Copied from original issue: Microsoft/Access2Justice#523_

**Comment by svasylenko** [comment]
![image](https://user-images.githubusercontent.com/46557859/51490472-082d0e00-1db4-11e9-8120-02c7c25acd47.png)

Verified

**Comment by KellyeDC-zz** [comment]
Issue resolved
