### ISSUE TITLE
Privacy related updates to UI

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#416]
_From @amitabhm21 on September 26, 2018 22:36_

@yfzwinnie This is the outline of the Privacy related updates needed to the UI. Need recommendation on what is the best approach, allocate time and get this done.

1.	Location Feature: 
a.	Add language to the pop-up: "we do not store your location information."  
b.	Remove privacy promise and language about sharing information (i.e. "we do not share your information…").  It implies that we are storing their location information which is not accurate. 
c.	Add language that the user need not provide an exact address.   

2.	Guided Assistant feature
a.	Add language below text box to notify users that there is no benefit to providing information about who you are (personally identifiable information).  However, providing relevant facts about your situation is useful.  The language should be friendly advise vs. a legal disclaimer and use super simple language (what do you need to know to use this).  
b.	The above language should be added wherever there is a free text field. 

3 Share a Profile or plan feature:  Add language to inform users to be mindful of who they share the plan or profile with.  Only share this with a trusted person.  Ex. "Anyone with this link will be able to access your information/plan"

4.	Download feature:	Add dialogue box, "is this your own computer. If yes, provide download option. if no, (i.e. shared computer), provide print option instead

_Copied from original issue: Microsoft/Access2Justice#524_

**Comment by grawdon** [comment]
These have all been added.
