### ISSUE TITLE
Feature/488 bad request

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#418]
_From @venkati-naidu on September 28, 2018 9:10_

Hi Winnie,
Fix for bug #488:Bad request when accessing Bing Maps API .

Please review and provide your comments.

Thanks,
Venkati Naidu

_Copied from original issue: Microsoft/Access2Justice/pull/527_

**Comment by aroubin** [comment]
_From @venkati-naidu on October 1, 2018 7:13_

Hi Winnie, Thanks for the valuable comments. Fixed the issue without Foreach loop and all unit tests are passing as well.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
