### ISSUE TITLE
Feature/482 rbac by user using custom permissions

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#428]
_From @charmila-c on October 5, 2018 11:45_

#481 #482 #483 

This PR includes 404_login_into_webApp PR #528  changes also. Please consider this PR after merging #528 PR.

Thanks

_Copied from original issue: Microsoft/Access2Justice/pull/540_

**Comment by aroubin** [comment]
_From @alaatadmori on October 11, 2018 5:18_

Closing this PR as there is a new version of it #557 .

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
