### ISSUE TITLE
As a Portal User, I need a quick summary of different services and resources that the portal can provide for me, so that I can make a decision on how I might use it (curated experience, select a topic, perform a search). 

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#43]
_From @czdiana2321 on May 10, 2018 18:21_

USER->UI

Acceptance Criteria:
1. Portal User is able to view the services offered by the portal.
2. The system is able to provide a link to Guided Assistant and Topics & Resources.

_Copied from original issue: Microsoft/Access2Justice#52_

**Comment by yfzwinnie** [comment]
Completed as part of MVP.
