### ISSUE TITLE
Feature544/create topics and resources e2e tests

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#433]
_From @xilin95 on October 8, 2018 20:58_

Only added 1 scenario: View Service Organizations in Your Community pane in Family topic. The other scenarios for Topics & Resources were included in a previous pull request.

_Copied from original issue: Microsoft/Access2Justice/pull/547_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
