### ISSUE TITLE
Develop kv

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#437]
_From @kapilzen on October 8, 2018 21:43_

Hi Reviewers,

I have added the code for Key Vault Integration and for now only used it with CosmosDb for Auth Key, Based on review comments, i will add for remaining classes like Bing, Luis etc.

_Copied from original issue: Microsoft/Access2Justice/pull/552_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
