### ISSUE TITLE
Feature/upgrading bootstrap

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#440]
_From @yfzwinnie on October 9, 2018 0:38_

- Upgrade Boostrap 3.3.7 to 4.1.3 to resolve XSS vulnerability.
- Fixed UI Bug: #496, #498, #500, #501, #502, #503, #504, #505, #506,  #508, #509, #510, #511,#548

_Copied from original issue: Microsoft/Access2Justice/pull/555_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
