### ISSUE TITLE
Imported content should support plain text with new line characters.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#444]
_From @aroubin on October 10, 2018 0:49_

In general, web site content (such as overview, description, etc...) fields should support plain text content with new line characters. A good example of this is an Overview section which can get fairly long, so line breaks will be needed to properly display the content, rather just a wall of text.

_Copied from original issue: Microsoft/Access2Justice#560_

**Comment by aroubin** [comment]
_From @vennasr on October 19, 2018 5:13_

As part of the #569 PR the issue got resolved

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
