### ISSUE TITLE
Organization layout does not render all fields

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#445]
_From @aroubin on October 10, 2018 0:52_

Organization template does not render all organization fields, such as Specialties and Qualifications, which have placeholder lorem ipsum. 

_Copied from original issue: Microsoft/Access2Justice#561_

**Comment by aroubin** [comment]
_From @SoniRathore on October 15, 2018 11:53_

Updated the Data Import Tool and made changes in API.

**Comment by KellyeDC-zz** [comment]
@KellyeDC to check with states for validation.

**Comment by Olgaivchenko** [comment]
@KellyeDC 
Kellye, please tell us what should be done here?

**Comment by KellyeDC** [comment]
@ozholob @yevhenobertas @svasylenko Please ensure that all fields for organizations (resourceType) renders on the screen, i.e. specialties, eligibility (where applicable).  Please reference Organization tab on the Resources spreadsheet for each state.

**Comment by ozholob** [comment]
@KellyeDC 
Hi, we've fixed this issue. 
See the screenshot below. (Resource is Organization)
![image](https://user-images.githubusercontent.com/55988406/72606796-f5e2a300-3927-11ea-8e30-fca5b4db8a47.png)
Please confirm
Thanks

**Comment by svasylenko** [comment]
N/A in address is due to:

![image](https://user-images.githubusercontent.com/46557859/72824693-65d19000-3c7e-11ea-8461-cfcd8e288248.png)

**Comment by KellyeDC** [comment]
Ready for review by PO

**Comment by grawdon** [comment]
@KellyeDC I looked at half a dozen organizations and all had all of the fields. It worked correctly.
