### ISSUE TITLE
Remove HTML tags from the curated experience questions

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#450]
_From @alaatadmori on October 10, 2018 22:27_

When we import the Curated Experience form A2J Author it comes with embedded HTML tags (i.e. <p> and <br/>...). We need to remove these tags upon importing the json.

_Copied from original issue: Microsoft/Access2Justice#568_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
