### ISSUE TITLE
commit after fixing share plan issue, as it was not displaying shared…

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#496]
_From @turpu-rakesh on October 15, 2018 10:37_

changes realted to 556 bug, I shared my profile but when I tried to open the permalink http://localhost:5150/share/782958E it is routing to login page.

_Copied from original issue: Microsoft/Access2Justice/pull/614_

**Comment by aroubin** [comment]
_From @turpu-rakesh on October 23, 2018 6:18_

Hi Alaa - Resolved conflicts, please review and merge.

Thanks,
Rakesh

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
