### ISSUE TITLE
Perform static content import

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#498]
_From @aroubin on October 15, 2018 22:34_

Perform import of static site content so that there is basline content available in the site.

_Copied from original issue: Microsoft/Access2Justice#616_

**Comment by aroubin** [comment]
_From @shandang on December 3, 2018 17:20_

Link to final static content.  Privacy Policy and stock images are still in development and is not available for upload at this time.  

https://docs.google.com/document/d/1YQkKF2iKL77q55fTxg4ZjAIxjkqtoWN28dO08L2Lo9k/edit?usp=sharing

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
