### ISSUE TITLE
Feature/web search issue pagination

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#507]
_From @turpu-rakesh on October 17, 2018 7:36_

pagination fix for web search

_Copied from original issue: Microsoft/Access2Justice/pull/625_

**Comment by aroubin** [comment]
_From @turpu-rakesh on October 17, 2018 7:37_

By mistake, I raised PR for master branch 👎 .

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
