### ISSUE TITLE
Fixed #532 bug - Search API does not return expected results

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#509]
_From @vennasr on October 17, 2018 10:45_

Fixed #532 bug - Search API does not return expected results. 
Added a logic to show the web links when there are, 
1) no proper LUIS Intent 
2) no mapping resources to specific LUIS Intent.

_Copied from original issue: Microsoft/Access2Justice/pull/627_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
