### ISSUE TITLE
fixed_failed jasmine test cases in topics and organzations component

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#511]
_From @durga-rajasekhar on October 17, 2018 13:7_

Hi Winnie,
Two jasmine test cases are failing in latest develop branch,I have fixed those  test cases.

_Copied from original issue: Microsoft/Access2Justice/pull/629_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
