### ISSUE TITLE
Curated Experience questions have unwanted tags(variable names)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#521]
_From @alaatadmori on October 21, 2018 6:30_

Some questions in the curated experience have tags similar to this: %%[Client first name TE]%% 
We need to remove these tags.

e.g. 
%%[Client first name TE]%% do you live in Alaska or Hawaii?

Should become:
do you live in Alaska or Hawaii?

_Copied from original issue: Microsoft/Access2Justice#642_

**Comment by KellyeDC-zz** [comment]
@grawdon Is this a valid defect?

**Comment by grawdon** [comment]
@KellyeDC Have we heard from either state that this is still an issue? The only way for us to test would be to do every Guided Assist with every permutation to see if it turned up. That's not practical.

**Comment by KellyeDC-zz** [comment]
Unable to test
