### ISSUE TITLE
"ParentTopicID" is replaced with "parentTopicId" to display topics

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#526]
_From @durga-rajasekhar on October 22, 2018 11:16_

#646

_Copied from original issue: Microsoft/Access2Justice/pull/647_

**Comment by aroubin** [comment]
_From @alaatadmori on October 23, 2018 4:23_

Closing this PR as the changes already made it to develop branch.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
