### ISSUE TITLE
Feature/538 api interface swagger documention

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#533]
_From @nehaljoshi212 on October 23, 2018 10:2_

_Copied from original issue: Microsoft/Access2Justice/pull/655_

**Comment by aroubin** [comment]
_From @msftclas on October 23, 2018 10:2_

[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/Microsoft/Access2Justice?pullRequest=655) <br/>All CLA requirements met.

**Comment by aroubin** [comment]
_From @nehaljoshi212 on October 26, 2018 6:17_

Hi Alaa,
Merge conflicts has been resolved and extra files have been moved out after merge. Please review now.
Thanks,
Nehal

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
