### ISSUE TITLE
Delete answer files after generating the personalized plan

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#544]
_From @alaatadmori on October 24, 2018 17:53_

The CuratedExperienceAnswers collection is getting so big so quickly because with each run of the curated experience a new answer file is generated. We should delete these files after the personalized plan is generated.

_Copied from original issue: Microsoft/Access2Justice#665_

**Comment by aroubin** [comment]
_From @alaatadmori on October 29, 2018 22:19_

I created a new collection in the db called "GuidedAssistantAnswers" where we will save the users input when they are clicking through the curated experience. We could create a function that deletes old files after certain number of days. If the user is logged in and chooses to save the curated experience somewhere in the middle we will save their answer file in the UserResources collection so we could retrieve that anytime the user comes back to continue working on the curated experience. There is already a task for this #540 .

**Comment by yfzwinnie** [comment]
See comment above
