### ISSUE TITLE
YouTube video not embedded in the iframe correctly

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#548]
_From @yfzwinnie on October 25, 2018 1:24_

Currently we cannot load YouTube videos because we need to manipulate the url prior to embedding them in the iframe. 

If the YouTube video url is: https://www.youtube.com/watch?v=3g1Tu2Ulrk0

We need to change it to this format: https://www.youtube.com/embed/3g1Tu2Ulrk0"

![image](https://user-images.githubusercontent.com/20545930/47470314-15892b00-d7ba-11e8-8a34-8c662a793c24.png)

_Copied from original issue: Microsoft/Access2Justice#671_

**Comment by svasylenko** [comment]
It is not embeded at all - just redirected to youtube.com.
@KellyeDC please suggest the page behaviour - shall we redirect (bad UX practice) or open it popup window?

**Comment by asaperski-gloriumtech** [comment]
Video playlists are embedded incorrectly. E.g. https://www.youtube.com/watch?v=bL6z7ejSIns&list=PL0xIiE6nJBTGHi-xysqYdaRtIvHKeYZn9&index=16&t=0s is embedded as https://www.youtube.com/embed/bL6z7ejSIns&amp;list=PL0xIiE6nJBTGHi-xysqYdaRtIvHKeYZn9&amp;index=16&amp;t=0s and it results in a playback error. Correct source should be https://www.youtube.com/embed/videoseries?list=PL0xIiE6nJBTGHi-xysqYdaRtIvHKeYZn9 - https://www.youtube.com/embed/videoseries?list=%Playlist id%

https://support.google.com/youtube/answer/171780?hl=en

**Comment by oleksandr-bytsiuk-gloriumtech** [comment]
@svasylenko I think this bug refers to resource detailed page (e.g. https://dev.legalnav.org/resource/203ea17b-2d51-45f0-af4f-a3faabf47518)

**Comment by KellyeDC-zz** [comment]
@grawdon Is there a preference for viewing videos?

**Comment by breeglej** [comment]
@KellyeDC - Videos appear to be fixed.

**Comment by KellyeDC-zz** [comment]
@breeglej The question is rather or not we want the videos embedded in the platform or linked out to YouTube for viewing.

**Comment by breeglej** [comment]
@KellyeDC - I think it's fine the way it is right now in dev.  I don't think we should spend any additional time on this.
