### ISSUE TITLE
Feature/12 luis intent with resource mapping

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#55]
_From @turpu-rakesh on May 17, 2018 14:54_

_Copied from original issue: Microsoft/Access2Justice/pull/71_

**Comment by aroubin** [comment]
_From @alaatadmori on May 23, 2018 19:57_

Closing this PR as the code will be pushed again under a broader scope feature branch - feature/56_Retrieve_Topics_Resources_And_Web_Searches

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
