### ISSUE TITLE
Setup Dev Database with proper documents.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#550]
_From @turpu-rakesh on October 25, 2018 7:35_

Currently the Db which we are using in Dev is having few legacy documents. Need to create new Db for Dev and it should contain only latest documents.

_Copied from original issue: Microsoft/Access2Justice#673_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
