### ISSUE TITLE
Bug No #671(YouTube video not embedded in the iframe correctly )

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#551]
_From @durga-rajasekhar on October 25, 2018 9:44_

Hi Winnie ,
I have fixed bug #671 and failed test case
Please review and provide comments if any.
Thanks.

_Copied from original issue: Microsoft/Access2Justice/pull/674_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
