### ISSUE TITLE
Remove html tags from curated experience questions with exception to text formatting

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#556]
_From @alaatadmori on October 26, 2018 5:24_

We want to remove all html tags from the curated experience questions except the following tags must be retained as is:
```
<a>
<b>
<u>
<i>
<br>
```

_Copied from original issue: Microsoft/Access2Justice#680_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
