### ISSUE TITLE
Feature/import tool changes

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#557]
_From @SoniRathore on October 26, 2018 5:25_

Changes included for #645:
1. Updated topic and resource guids back into topic and report templates.
2. Renamed Access2JusticeCode to Access2Justice to maintain consistency.

_Copied from original issue: Microsoft/Access2Justice/pull/681_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
