### ISSUE TITLE
externalUrl issue fixed

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#558]
_From @venkati-naidu on October 26, 2018 14:22_

Hi Alaa / Winnie,
Issue: Bug#651 Remove externalUrl property from Resources 
Please review and provide your comments if any.
Thanks

_Copied from original issue: Microsoft/Access2Justice/pull/682_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
