### ISSUE TITLE
As Portal User, I need to be able to filter my search results by type so that I can quickly get to the correct resource type(s). 

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#56]
_From @czdiana2321 on May 17, 2018 17:38_

1.Portal User is able to filter the search results by type to quickly get to the correct resource  and content
	• Topic
	• Location (State, City, ZIP)
	• Type of resource 
	• Media Type
	• Date (Newest to Oldest)
	• Sorting (A to Z)
2.When the metadata is not available for filter the results should be visually distinguished to separate filtered results and "other relevant" content.

_Copied from original issue: Microsoft/Access2Justice#72_

**Comment by svasylenko** [comment]
Verified
![image](https://user-images.githubusercontent.com/46557859/52054570-aadc4e00-2565-11e9-8aa2-178caf9ba3d5.png)

**Comment by KellyeDC-zz** [comment]
@grawdon and @breeglej  Let's review and determine if we need to create user stories to update the filters for search results.

**Comment by konstantin-orekhov** [comment]
07/19 - 8h

**Comment by konstantin-orekhov** [comment]
07/22 -2h

**Comment by konstantin-orekhov** [comment]
In the old version, the search didn't work properly.
We used in BackendDatabaseService.QueryResourcesCountAsync function GetFirstPageResourceAsync(query, parameters, true) this function was returning the only first page with resources, not all resources.  In the new version, I replaced  function GetFirstPageResourceAsync(query, parameters, true) with function QueryItemsAsync(cosmosDbSettings.ResourcesCollectionId,query, parameters). Now we are returning all resources and can be creating tiles with properly count of the resources.  I think in this situation we don't need to add  "other relevant". Please check this.

**Comment by KellyeDC-zz** [comment]
In Stage,, all of these filters are not available for the platform user.  @grawdon Do we still want this feature for the platform?

**Comment by KellyeDC-zz** [comment]
<img width="908" alt="Issue 56 platform user filter" src="https://user-images.githubusercontent.com/45771252/66168114-4862b280-e60a-11e9-9425-71c09ec889c6.PNG">

**Comment by grawdon** [comment]
I don't see date. Changing the location does seem to work. If I search for all of Hawaii first and then narrow down by zip, it does return resources.

**Comment by grawdon** [comment]
@KellyeDC Did we decide to eliminate sorting by Date?

**Comment by grawdon** [comment]
Never mind, I found Date. It was an option in Sort.
