### ISSUE TITLE
Feature/remove external url from import tool

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#570]
_From @SoniRathore on October 29, 2018 11:49_

This PR includes changes for task #695:
1. Used shared topic, resource and location model for data import tool project. so that all projects uses common model.

2. Removed icon field from resource.

_Copied from original issue: Microsoft/Access2Justice/pull/696_

**Comment by aroubin** [comment]
_From @SoniRathore on October 30, 2018 4:59_

Thanks Alaa for review.

We are removing icon field from resources as icon wont change for each resource and UI is not using this field to show icon.

To remove redudendent code, data import tool will leverage Topic, Resource and Location model from shared project which is being used accross all other projects.

I have removed externalUrl and icon property from Resources collection in cosmos db. Thanks for reminding me.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
