### ISSUE TITLE
All resources missing from "Green Cards (Visas and green cards)" topics.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#572]
_From @shandang on October 29, 2018 16:37_

Data may not be mapping due to case sensitivity issue?  Also, the topic spelling on the resources spreadsheet matches topic defined in the topic spreadsheet.  It is in the UI that the spellings are different. 

<Green Cards (Visas and green cards)> on spreadsheet vs.  <Green Cards (Visas And Green Cards)> in the UI (the word And should never be capitalized in the English language).  If this is a case sensitivity issue, please change the backend to match the spreadsheet as that is the correct version.

_Copied from original issue: Microsoft/Access2Justice#698_

**Comment by aroubin** [comment]
_From @AnnaK111 on October 30, 2018 19:20_

On the dev server I see "Green Cards (Visas and green cards)" in the Immigration level. But if I click that category, it's "Green Cards (Visas And Green Cards)". Should be consistent. Also maybe a good idea to define a consistent style for all headings: Sentence caps (The dish ran away) or title caps (The Dish Ran Away). Sentence caps are usually more user friendly and easier to read.

**Comment by aroubin** [comment]
_From @shandang on October 30, 2018 21:9_

@AnnaK111, agreed, need consistency.  Winnie is applying stylizing to the detailed page.  She is going to revert back so it matches what is at the topic level, which also maps to how the topics are defined in the spreadsheet.  Still need to resolve the missing data.

**Comment by aroubin** [comment]
_From @SoniRathore on October 31, 2018 9:59_

In template, this topic is split across 2 lines which is causing \n between topic name in imported topic. in DB topic name is stored as 'Green Cards \n(Visas and green cards)'

![image](https://user-images.githubusercontent.com/37994521/47780543-964ba800-dd21-11e8-8a88-49773f6a4093.png)

To avoid this, content admin should fill topic name in single line.

Updated topic name from Green Cards \n(Visas and green cards)' to Green Cards (Visas and green cards)'.

Now resources are displayed in UI for this topic.

**Comment by aroubin** [comment]
_From @shandang on October 31, 2018 22:47_

Got it.  Thank you!

**Comment by aroubin** [comment]
_From @AnnaK111 on November 2, 2018 16:39_

Fixed in dev: Writing is style is consistent, data is showing up.

**Comment by aroubin** [comment]
_From @shandang on November 2, 2018 18:40_

Fix confirmed.  Issue closed.

**Comment by svasylenko** [comment]
We could not reproduce the issue.
