### ISSUE TITLE
Resources are not displaying for "Becoming a U.S. Citizen (Citizenship)" topic.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#573]
_From @shandang on October 29, 2018 16:45_

This may be due to case sensitivity.  The correct category is <Becoming a U.S Citizen (Citizenship)>.  Not <Becoming A U.S. Citizen (Citizenship)>. The work "A" should not be capitalized.

_Copied from original issue: Microsoft/Access2Justice#699_

**Comment by aroubin** [comment]
_From @SoniRathore on October 31, 2018 9:53_

In template, this topic is split across 2 lines which is causing \n between topic name in imported topic. in DB topic name is stored as 'Becoming a U.S. Citizen \n(Citizenship)'

![image](https://user-images.githubusercontent.com/37994521/47768852-b7030600-dcff-11e8-8e09-0cb24a65d4c2.png)

To avoid this, content admin should fill topic name in single line.

Updated topic name from 'Becoming a U.S. Citizen \n(Citizenship)' to 'Becoming a U.S. Citizen(Citizenship)'.

Now resources are displayed in UI for this topic.

**Comment by aroubin** [comment]
_From @shandang on October 31, 2018 21:50_

Perfect.  Thanks Soni!

**Comment by aroubin** [comment]
_From @AnnaK111 on November 2, 2018 16:41_

Fixed as of 11.2: Spelling consistent, data is showing up.

**Comment by svasylenko** [comment]
To be tested within next resouce upload.

**Comment by svasylenko** [comment]
We could not reproduce the issue.
