### ISSUE TITLE
Added redirection for related links and essential reading resources. …

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#582]
_From @SoniRathore on October 30, 2018 11:37_

Changes included in this PR:
1. Page redirection to url for Related Links and Essential Readings. #694 
2. Fixed Organization reviewer bug. #701 

_Copied from original issue: Microsoft/Access2Justice/pull/709_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
