### ISSUE TITLE
Task_446(Need to create UI to show parent subtopic page as a link)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#583]
_From @durga-rajasekhar on October 30, 2018 13:11_

Hi Winnie,
#446
Please review and provide comments if any.

_Copied from original issue: Microsoft/Access2Justice/pull/710_

**Comment by aroubin** [comment]
_From @yfzwinnie on October 31, 2018 22:24_

Per Shandan and Carly, we will not have any information for L1 (parent topic) details.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
