### ISSUE TITLE
639 admin page to upload curated exp package

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#584]
_From @vennasr on October 30, 2018 18:28_

Added new admin component to import the a2j author templates to cosmos db. #639 

_Copied from original issue: Microsoft/Access2Justice/pull/713_

**Comment by aroubin** [comment]
_From @vennasr on November 5, 2018 13:16_

Hi Alaa/Winnie,

I have pulled the latest develop and resolved the conflicts. 
Updated the admin component as per the newly created structure.
Added component unit test creation, all the angular unit tests are passing.
I have uploaded the newly provided attachment and file is uploaded successfully. 

Observation: In Guided Assistant flow, some of the questions are not appearing where as the options are displaying. Search "Protective Order" and select the second result from the Guided Assistant Tab results and please check the flow.
Note: Once the code is merged will ask one of the junior developer to write the back end unit test case. 

Thanks,
Sateesh Reddy

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
