### ISSUE TITLE
Update routing for topics and resources page (US#14 SP#3)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#59]
_From @yfzwinnie on May 17, 2018 21:17_

Routing for topics and resources page should follow:
- For the list of topics page: ... /topics
- For the list of subtopics page: ..../topics/{guid}
- For the subtopic detail page: ..../topics/{guid}
- For the individual resource page (action plan, article, etc.): ..../resources/{guid}

_Copied from original issue: Microsoft/Access2Justice#75_

**Comment by aroubin** [comment]
_From @yfzwinnie on June 21, 2018 22:38_

Completed code review with Andrew and Alaa. Moving this to resolved.

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
