### ISSUE TITLE
WCAG 2.4.6 Headings and Labels: Indicate Required Fields in Guided Assistant

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#590]
_From @xilin95 on October 31, 2018 1:58_

**A form with required fields**
A form contains several required fields. The labels for the required fields are displayed in red. In addition, at the end of each label is an asterisk character, *. The instructions for completing the form indicate that "all required fields are displayed in red and marked with an asterisk *", followed by an example.

**A form that uses color and text to indicate required fields**
A form contains both required and optional fields. Instructions at the top of the form explain that required fields are labeled with red text and also with an icon whose text alternative says, "Required." Both the red text and the icon are programmatically associated with the appropriate form fields so that assistive technology users can determine the required fields.

**For more info: check https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships**

_Copied from original issue: Microsoft/Access2Justice#719_

**Comment by KellyeDC-zz** [comment]
@grawdon aand @breeglej Is ths needed for pilot?

**Comment by breeglej** [comment]
@KellyeDC @grawdon - I don't think this is needed for pilot.  I think we should put it on hold.
