### ISSUE TITLE
WCAG 3.3.3 Error Suggestion

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#596]
_From @xilin95 on October 31, 2018 20:32_

Give user hints to solve their input error in search. Like Google's Did you mean. 

**Checked with Winnie: we are not fixing this one.**

_Copied from original issue: Microsoft/Access2Justice#729_

**Comment by yfzwinnie** [comment]
Added input validation to guided assistant search and map search:

![image](https://user-images.githubusercontent.com/20545930/51769150-3e1e0b00-20b0-11e9-8698-26db52398aa7.png)
![image](https://user-images.githubusercontent.com/20545930/51769213-79203e80-20b0-11e9-8db6-6a23e7f40a7c.png)

**Comment by KellyeDC-zz** [comment]
Resolved/closed
