### ISSUE TITLE
API route refactoring

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#598]
_From @aroubin on October 31, 2018 22:28_

Need to refactor API routes to follow these general naming conventions: 

	1. kebab-casing
	2. Path ends with a verb (not needed if method is a GET)
	3. Pluralized name
	
Changes needed:

	- /curated-experience/component/ --> /curated-experiences/components
	- /personalized-plan/ --> /personalized-plans/
	- /personalized-plan/get-plan --> /personalized-plans (since GET is implied by the verb)
	- /share/*permalink methods --> /share/permalink/check , /share/permalink/generate, /share/permalink/, /share/permalink/remove
	- /static-resource/ --> /static-resources/
	- Refactor API methods for specific pages:
		○ /static-resources/home/upsert
		○ /static-resources/help-and-faq/upsert
		○ Etc…
	- /topics/create-resources/upload --> /topics/resources/upload
	-  /topics/upload
	- /topics/get-all-topics --> /topics/
	- /topics/get-breadcrumbs/{id} --> /topics/{id}/parent/
	- /topics/get-document --> /topics/document/
	- /topics/get-organization-details --> /topics/organizations/ 
	- /topic/get-resource-details --> /topics/resources/ 
	- *get-schema --> /schema. e.g. /topics/get-schema-action-plan --> /topics/schema 
	- /topics/get-subtopics/ --> /topics/subtopics/
	- /upsertresource --> /resources/upsert/
	- /upsert-resource-document/ --> /resources/document/upsert
	- /upserttopic --> /topic/upsert
	- /upsert-topic-document --> /topic/document/upsert
	- /user/get-user-profile --> /user/profile{oid> (GET)
	- /user/upsert-user-personalized-plan/ --> user/profile{oid}/plan 
/user/upsert-user-profile --> user/profile (POST)

_Copied from original issue: Microsoft/Access2Justice#732_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
