### ISSUE TITLE
Merging progress for US #14

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#60]
_From @yfzwinnie on May 18, 2018 22:29_

This pull request includes the following tasks:
- #25 Create UI for topic & resources page
- #48 Create UI for Sub topic page
- #26 Create UI for individual topics page
- #28 Create backend service
- #27 Create control for homepage to list topics

This does not include:
- front-end unit testing (started but not complete)

_Copied from original issue: Microsoft/Access2Justice/pull/77_

**Comment by aroubin** [comment]
_From @yfzwinnie on June 4, 2018 20:48_

Closing this pull request since this is encompassed in PR #112 .

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
