### ISSUE TITLE
Added environment specific clientid's for oAuth.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#601]
_From @vennasr on November 1, 2018 11:33_

Added environment specific clientid's for oAuth. While deployment please use the updated values specific to each environment until we update this in CI/CD process. or find a better solution. If we will not use the proper id's then the user cannot save the resources/cannot login to the system.

_Copied from original issue: Microsoft/Access2Justice/pull/736_

**Comment by aroubin** [comment]
_From @vennasr on November 5, 2018 11:21_

Hi Alaa, I have created a Task and update the changes required in the Deployment section in the Teams. Sent a mail to Andrew.  Thank you!

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
