### ISSUE TITLE
As Portal User, I need to fill out an onboarding form for service provider of my choice

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#609]
_From @aroubin on November 2, 2018 3:34_

1. Portal user goes through curated experience. 
2. Service Provider organizations are shown as recommended next steps. 
3. User selects organization and chooses to onboard
4. Portal shows dynamically generated list of onboarding questions that the selected provider requires (e.g. name, address, phone number, living situation).
5. User fills out dynamic form. 
6. Portal creates a referral record (for feedback tracking) and sends collected information to service provider (via configured transport such as email or web api call). 
7. User receives confirmation that information has been sent. 

_Copied from original issue: Microsoft/Access2Justice#744_

**Comment by aroubin** [comment]
_From @vennasr on November 6, 2018 4:48_

#745 
#746 
#747 
#748 
#749

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
