### ISSUE TITLE
Update Organization card / detail to show that organization supports automatic onboarding. (US #744)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#610]
_From @aroubin on November 2, 2018 3:37_

For organizations that support automated onboarding, show icon / button allowing user to begin the onboarding process.

_Copied from original issue: Microsoft/Access2Justice#745_

**Comment by aroubin** [comment]
_From @venkati-naidu on November 19, 2018 12:57_

Some inputs from Andrew:
Task#745 : Update Organization card / detail to show that organization supports automatic onboarding. (US #744) : For organizations that support automated onboarding, show icon / button allowing user to begin the onboarding process.
 
Queries:
1.	Where do we make provision  (i.e. upper nav bar ?) on our portal to display the icon/button for onboarding organization?
 
AR: placement not particularly important, but let us consult with @Winnie Zhang on that.
 
 
2.	Do we need to consider the registered user only allow to create organization? So that icon/button will be visible after user login?
 
AR: I am not sure I understand the question. We are not creating organizations, we are just providing user with ability to onboard with an organization (collect name/value pairs for known fields). For example, imagine that a legal help organization wants to expedite onboarding process for incoming referrals, so it wants to collect the following info from all new clients: Name, Phone, Age, Gender. So for this organization we would have 4 fields defined, and we would need to dynamically render these fields to collect the input from the user. Once user provides that information, we would forward it on to the service provider using their preferred transport (such as web API call, but could be email or something else).

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
