### ISSUE TITLE
Implement API methods to retrieve service provider onboarding information (US #744)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#611]
_From @aroubin on November 2, 2018 3:39_

Implement API methods that will allow web app to retrieve list of fields required by the organization for onboarding so that the web app can render them for the user.

_Copied from original issue: Microsoft/Access2Justice#746_

**Comment by aroubin** [comment]
_From @venkati-naidu on November 19, 2018 12:59_

Some inputs from Andrew:
Task#746: Implement API methods to retrieve service provider onboarding information (US #744) : Implement API methods that will allow web app to retrieve list of fields required by the organization for onboarding so that the web app can render them for the user:
 
Queries:
 
1.	Do we  need to consider the fields like applicant's name, address, phone number, and a note? Are we make provision for organization website url and logo/icon fields as well?
AR: fields could be whatever the provider wants to collect. Could be eye color or favorite dog breed, if they think that is important. We are just collecting the info for these dynamically provisioned fields and once we have this information, we are just sending these name / value pairs to the service provider. Everything happens in our UI that is rendered dynamically based on provider configuration. 
 
2.	Assuming user’s location is the base location of the organization
AR: it does not have to be. User can onboard to any organization they choose to. 
 
3.	Do we need to create separate collection for the onboarding organization.
AR: Take a look at the definition of ServiceProvider class which extends Organization (in 530_Adaptor_Design branch). I think it is easier to store it in the same collection as the rest of the organizations.

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
