### ISSUE TITLE
Implement sample Service Provider API that will receive onboarding information from the user. (US #744)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#612]
_From @aroubin on November 2, 2018 3:44_

For demonstration purposes, create a "dummy" web service that would serve as an example of what a service provider organization might expose as an endpoint for onboarding users that require their services. 
In the simplest form, it could be a web API method that takes a POST consisting of applicant's name, address, phone number, and a note. The service could log the received information to a text file. 
Publish this sample API app as a separate app in a new resource group, create/update any necessary scripts for resource creation in Azure. 

_Copied from original issue: Microsoft/Access2Justice#747_

**Comment by aroubin** [comment]
_From @venkati-naidu on November 19, 2018 13:0_

Some inputs from Andrew:
Task#747: Implement sample Service Provider API that will receive onboarding information from the user. (US #744) :
 
Queries:
 
1.	The service  will have api methods for create / update onboarding organization.
AR: no, this is demo code to illustrate that some providers may already have endpoints that they use to onboard users. 99% of organizations will not have this, they are not that sophisticated. Most won’t have anything like that at all. Some might have an email inbox. But for this exercise, let us mock up a pretend web API that a more tech savvy service provider could have for their back end systems. 
In either way, this is service provider’s “inbox” that they use to onboard clients. They would receive name/value pairs of the information collected from the users and expedite onboarding. 
 
2.	The service could log the received information to a text file – could you please elaborate.
AR: After the service provider receives the name / value pairs of onboarding information, what they do with it is entirely up to them. But since this is a demo web site, we could write each received application to a text file just so that we can demonstrate that the information that was collected from the user was received. 
 
3.	Publish this sample API app as a separate app in a new resource group, create/update any necessary scripts for resource creation in Azure – could you please elaborate.
AR: since this is a demo web API and not part of our platform code, we just need to publish it as another web app (let’s say DemoServiceProviderApi) to illustrate how our platform would hand over collected user onboarding information to an external web site.

**Comment by breeglej** [comment]
@KellyeDC - This doesn’t have to be done for pilot.
