### ISSUE TITLE
Implement API methods for receiving user onboarding info and forwarding to service provider. (US #744)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#614]
_From @aroubin on November 2, 2018 3:50_

This API method needs to receive name / value pairs from dynamically generated web UI shown to the user during onboarding. Once information is received, it needs to be forwarded to indicated service provider using the supported transport. 

_Copied from original issue: Microsoft/Access2Justice#749_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
