### ISSUE TITLE
Feature/admin ui

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#618]
_From @yfzwinnie on November 2, 2018 16:4_

This PR created the foundation for tasks #140 and #90. I have restricted access to admin routes and created a privacy & about edit page. However, still need to work on:
- restricting access to children routes (admin/privacy, admin/about... etc) to only admins in the organizational unit
- pass in state parameter so static resource are loaded for only the state admin in the organizational unit

Opened a separate task for the remaining work: #752

_Copied from original issue: Microsoft/Access2Justice/pull/753_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
