### ISSUE TITLE
As Portal User, I need to access Help and FAQ session so that I can see if my question about the portal has already been addressed. 

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#62]
_From @czdiana2321 on May 21, 2018 19:36_

USER->UI

Acceptance Criteria:
1.Portal User is taken to the Help and FAQ Page
2. Portal User is able to view and browse the list of questions and answers.

_Copied from original issue: Microsoft/Access2Justice#79_

**Comment by yfzwinnie** [comment]
Completed as part of MVP.

**Comment by KellyeDC-zz** [comment]
@grawdon and @breeglej Is this "complete"?  Are these features to be further developed over time?

**Comment by breeglej** [comment]
@KellyeDC @grawdon  - I don't see what else we could do with this right now.  We will have to add to the FAQs over time.

**Comment by KellyeDC-zz** [comment]
Agreed.  Should we add a placeholder to continue Q&A development?

Kellye Bennett
Legal Navigator Project Manager
Legal Services Corporation
[cid:image001.jpg@01D4FB74.11D4BDC0]
Office of Information Technology
3333 K Street, NW
Washington, DC 20007
P: 202.295.1569
E: bennettk@lsc.gov<mailto:bennettk@lsc.gov>

**Comment by breeglej** [comment]
@KellyeDC - It might be more of a task in our Smartsheet as it is not development.

**Comment by KellyeDC-zz** [comment]
Thanks! I’ll add it

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by KellyeDC-zz** [comment]
These items will be updated through the admin portal for static content.
