### ISSUE TITLE
Feature/bug fix

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#623]
_From @SoniRathore on November 5, 2018 6:20_

This PR includes following changes.

1. Moved API host name to app.config
2. Updated tool as per changed resource schema from Urls to Url.
3. Updated naming conventions for Model to singular form.
4. Moved sheet names to constants to remove duplicate code.

_Copied from original issue: Microsoft/Access2Justice/pull/758_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
