### ISSUE TITLE
Feature/631 save personalized plan without signedin

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#630]
_From @charmila-c on November 6, 2018 6:10_

#631 #638 

_Copied from original issue: Microsoft/Access2Justice/pull/765_

**Comment by aroubin** [comment]
_From @yfzwinnie on November 26, 2018 19:39_

@charmila-c  After logging in, saving a resource/topic will overwrite all the old saved resources. Please fix!

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
