### ISSUE TITLE
Feature/732 api route refactoring

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#632]
_From @SoniRathore on November 6, 2018 10:25_

This PR includes changes for:
API route refactoring (#732)

There are 3 routes in api.ts file which doesn't exists in any of the controller.
planUrl: curatedExperience + "/get-plan-details"
updatePlanUrl: userProfile + "/upsert-user-plan"
updateUserPlanUrl: curatedExperience + "/update-plan"

Should we remove them?

_Copied from original issue: Microsoft/Access2Justice/pull/767_

**Comment by aroubin** [comment]
@SoniRathore  - when did these routes become obsolete? If that is the case we should definitely refactor them away.

**Comment by aroubin** [comment]
_From @SoniRathore on November 12, 2018 15:10_

@aroubin while removing these routes, personalized plan code is breaking. @vennasr  and @charmila-c  are working on personalized plan and they will take care to remove these unwanted routes.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
