### ISSUE TITLE
AppInsights implemented

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#633]
_From @venkati-naidu on November 6, 2018 13:40_

Task#531 : Update AppInsights for Usage Analytics #531

Hi Alaa, I have implemented the app insights log in  existing try/catch blocks only. As the Try/catch blocks were placed in required APIs so I considered those APIs and implemented. Please let me know if any concerns. 
Thanks,

_Copied from original issue: Microsoft/Access2Justice/pull/768_

**Comment by aroubin** [comment]
_From @alaatadmori on November 6, 2018 20:59_

@aroubin do we need to add this key to the key value or it's ok to keep it in the appsettings? Thank you.

`  "ApplicationInsights": {
    "InstrumentationKey": "809bdd52-ff08-48a1-81da-9c2dbf491875"
  }`

**Comment by aroubin** [comment]
_From @alaatadmori on November 9, 2018 5:18_

Closing this PR as we don't need to add custom code to the solution for logging exceptions, we will depend on App Insights built-in telemetry as it is more comprehensive.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
