### ISSUE TITLE
Add the following legal disclaimer below the Guided Assistant text box/entry point: 

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#635]
_From @shandang on November 6, 2018 20:50_

Please provide information for the subject areas for which you are seeking assistance, there is no need to provide personal information in the search field. This portal will not store any information you enter, however, any data you submit may otherwise be accessed or transferred.

_Copied from original issue: Microsoft/Access2Justice#770_

**Comment by KellyeDC-zz** [comment]
Reviewed and confirmed complete
