### ISSUE TITLE
Home page: use interactive elements and ensure tab sequence is right

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#637]
_From @xilin95 on November 7, 2018 22:58_

Related to:
- **Issue https://github.com/Microsoft/Access2Justice/issues/683** (has detailed descriptions of what I changed) 
WCAG 2.1.1 Keyboard: Review Site to Use Native HTML Tags Instead of Generic Divs or Spans (Home page)
- **Issue https://github.com/Microsoft/Access2Justice/issues/703** WCAG 2.1.1 Ensure User Can Linearly Navigate the Site with Tabs

_Copied from original issue: Microsoft/Access2Justice/pull/772_

**Comment by aroubin** [comment]
_From @xilin95 on November 30, 2018 17:47_

Linked to PR #855.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
