### ISSUE TITLE
Implement Azure Batch job for pulling RTM Service Provider data through ServiceProviderAdaptor (US #530)

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#641]
_From @aroubin on November 8, 2018 5:1_

Create Azure Batch job for connecting to RTM with ServiceProviderAdapter and poking data into A2J Integration API. Dependent on #743  and #764 

_Copied from original issue: Microsoft/Access2Justice#776_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
