### ISSUE TITLE
As Portal User, I want to see a message displayed in the portal when I entered a location so that I would know if it is supported or not supported.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#65]
_From @czdiana2321 on May 21, 2018 19:39_

USER->UI

Acceptance Criteria:
1. The system is able to display content that is relevant globally.
2. The system is able to display a message if the location entered is supported or not.
3. The Portal User is able to enter location to display content that is relevant globally.
4. The Portal User is able to view a message if the location entered is supported or not supported.

_Copied from original issue: Microsoft/Access2Justice#82_

**Comment by KellyeDC-zz** [comment]
Issue resolved.
