### ISSUE TITLE
Feature/768 configure app insights api project

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#650]
_From @alaatadmori on November 9, 2018 21:19_

Hi Andrew, I added App Inisghts to both the Api and the Web projects and remove all the empty try/catch block from the api code.
Also, I did some refactoring around saving the answer files.
Please note that there are a lot of spacing issues that I fixed so many of these diff lines are just space diff.
Please have a look. Thanks!

p.s. I just deployed the latest and the greatest code to dev environment.

_Copied from original issue: Microsoft/Access2Justice/pull/788_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
