### ISSUE TITLE
Feature/764 crud ap is adapter pattern

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#653]
_From @SoniRathore on November 16, 2018 11:51_

Implemented CRUD APIs for service providers (Task #764).

_Copied from original issue: Microsoft/Access2Justice/pull/795_

**Comment by aroubin** [comment]
_From @SoniRathore on November 20, 2018 10:35_

If we don't maintain siteId, what should be criteria to check whether record exist in our Db or not?

**Comment by aroubin** [comment]
_From @SoniRathore on November 22, 2018 8:28_

Implemented suggested changes as per discussion. Also changed siteId to externalId so identify that records exist in our db or not.

**Comment by aroubin** [comment]
_From @alaatadmori on November 28, 2018 6:31_

Closing this PR as this code was merged into a new branch (feature/530_Adaptor_Design) and another PR will be created from that branch. Code comment in this PR are addresses in feature/530_Adaptor_Design.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
