### ISSUE TITLE
resolved warnings

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#661]
_From @xilin95 on November 26, 2018 22:36_

**Changes:**
- In **Hooks.cs** file, I made the fields private instead of protected because of IntelliSense warning that making fields protected in a sealed class provides no extra benefits.
- In the **other three files**, I initialized fields as null to get rid of the "fields not initialized" warnings.

_Copied from original issue: Microsoft/Access2Justice/pull/808_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
