### ISSUE TITLE
As Portal User, I need to login to my profile so that I can access my saved information (plan and profile settings).

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#67]
_From @czdiana2321 on May 21, 2018 21:19_

USER->Profile

Acceptance Criteria:

Portal User is able to login with Outlook.com credentials to access the profile.
1. User selects the Login link the the UI
2. User is redirected to Outlook.com for login
3. After login, if the user is first time visitor to the site, they are prompted to create profile consisting of First Name, Last Name and Email

_Copied from original issue: Microsoft/Access2Justice#85_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh
