### ISSUE TITLE
Feature/530 adaptor design cleanup

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#684]
_From @alaatadmori on November 27, 2018 22:40_

In this PR i removed the RTM specific code/settings from the Api project and renamed the RTM classes in the Integration project to make it clear they are RTM-specific. I also cleaned up some of the codes in these 2 projects.

_Copied from original issue: Microsoft/Access2Justice/pull/831_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
