### ISSUE TITLE
Data Import tool enhancements

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#687]
_From @SoniRathore on November 28, 2018 10:11_

Below changes are required in data import tool.
1. Tool should be able to process Integer data such as zipcode.
2. Tool should be able to process records if count of records is =>100 in excel sheet.

_Copied from original issue: Microsoft/Access2Justice#836_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
