### ISSUE TITLE
dynamic type doesn't have a definition of 'count' so it is throwing a…

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#692]
_From @alaatadmori on November 28, 2018 22:53_

fixed a bug in PR #800 . (Dynamic are resolved to an object that doesn't have a definition of 'count')

_Copied from original issue: Microsoft/Access2Justice/pull/844_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
