### ISSUE TITLE
Fix Bing map errors

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#693]
_From @yfzwinnie on November 28, 2018 23:7_

We currently have a few errors related to Bing map on the console:
1. This error appears after you update the global location when you first enter the site **[Fixed]**
![image](https://user-images.githubusercontent.com/20545930/49188510-df424c80-f31f-11e8-8766-36b46676dc05.png)

2. Navigate to http://localhost:5150/topics/ef602bd3-527c-435b-b3d1-3561495e378a then click on "See more organizations" **[Fixed]**
![image](https://user-images.githubusercontent.com/20545930/49188553-0731b000-f320-11e8-8bb5-1941ec9288b1.png)

_Copied from original issue: Microsoft/Access2Justice#845_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
