### ISSUE TITLE
Bing search does not return results

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#695]
_From @aroubin on November 29, 2018 5:17_

Typing a question in Guided Assistant results in no intent match. There should still be Bing search results displayed though. 

_Copied from original issue: Microsoft/Access2Justice#847_

**Comment by svasylenko** [comment]
Verified.

![image](https://user-images.githubusercontent.com/46557859/51535222-82ab6b80-1e50-11e9-9e76-8546659a7377.png)

**Comment by svasylenko** [comment]
Steps to reproduce: enter Divorce to search - following page is opened.

**Comment by KellyeDC-zz** [comment]
Issue resolved
