### ISSUE TITLE
Bug/683 homepage navigation

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#702]
_From @xilin95 on November 30, 2018 17:47_

Related to PR #772 
Related to Task #683 and #703 

**Achieved:**
- Fixed keyboard navigation on home page, including the upper and lower navigation and footer.

**Remaining Issues on home page that will be addressed separately:**
- Allowing keyboard navigation for carousel slides (task #843)
- Optimizing keyboard navigation on topics section (task #834)

_Copied from original issue: Microsoft/Access2Justice/pull/855_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
