### ISSUE TITLE
Bug/834 tab thru main topics page

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#703]
_From @xilin95 on December 1, 2018 0:42_

**Achieved:**
- In **topics.component.html**, I combined separate anchor tags into one, storing both the image and topic name. Grouping the label and image together lets user have a better navigation experience. 
- In the **Topics & Resources** page, the outline around each topic block looks fine when window is at full screen. 

**Remaining Issue:**
- In the **Topics & Resources** page, css style changes in **.topic-outline** in **topics.component.css** file messed up the layout when window size is adjusted to 1024 x 992. 

![capture](https://user-images.githubusercontent.com/19892495/49321777-80670980-f4be-11e8-8b29-d0125d81fa11.PNG)

- In **home page under the Topics section**, the outline is not perfect. 
![capture](https://user-images.githubusercontent.com/19892495/49321803-b1473e80-f4be-11e8-8a5c-6f065cdf549c.PNG)

_Copied from original issue: Microsoft/Access2Justice/pull/856_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
