### ISSUE TITLE
App is not loading on Internet Explorer

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#706]
_From @yfzwinnie on December 3, 2018 20:8_

This is happening on local and the deployed site. We need to add logic to check if broswer is internet explorer. If yes, display: 

"This browser is currently not supported. Please open the app using Chrome"

Chrome should be a link to the Chrome install site.

![image](https://user-images.githubusercontent.com/20545930/49399237-9f031580-f6f5-11e8-99f2-0ca011f4944b.png)

_Copied from original issue: Microsoft/Access2Justice#861_

**Comment by svasylenko** [comment]
PO Comment.

![image](https://user-images.githubusercontent.com/46557859/52494966-077be080-2bd8-11e9-8f51-771b9e7ce33a.png)

**Comment by svasylenko** [comment]
In IE a notification popup is open saying "Sorry, this browser is not supported". In all other bowsers (Edge, Chrome etc) it works.

**Comment by KellyeDC-zz** [comment]
Not required for IE
