### ISSUE TITLE
Create api endpoint for Personalized Plan page static content

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#707]
_From @yfzwinnie on December 3, 2018 21:32_

The following data should be coming from the database:

![image](https://user-images.githubusercontent.com/20545930/49402874-04f49a80-f700-11e8-90e3-610d297de1ba.png)

_Copied from original issue: Microsoft/Access2Justice#862_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
