### ISSUE TITLE
URLs and line breaks are not rendered

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#708]
_From @aroubin on December 4, 2018 20:48_

Excel sheet has link breaks in article section. Line breaks are not preserved. URLs are also rendered as plain text. 

article URL:
https://a2jdevweb.azurewebsites.net/resource/94b38bfc-3f31-4039-a71f-d58bda34e7b1

![image](https://user-images.githubusercontent.com/1211373/49472014-3da97800-f7c3-11e8-9451-b4b0d1eb4032.png)

contents in Excel: 

![image](https://user-images.githubusercontent.com/1211373/49472080-65004500-f7c3-11e8-8589-75b1685f4fe9.png)

_Copied from original issue: Microsoft/Access2Justice#864_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
