### ISSUE TITLE
Create endpoint to allow admin to edit personalized plan static content

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#710]
_From @yfzwinnie on December 5, 2018 4:38_

We need to create a static-resources/personalized-plan/upsert endpoint to allow admin to edit personalized-plan static contents.

Refer to branch admin-about to see similar implementation https://github.com/Microsoft/Access2Justice/tree/feature/admin-about

_Copied from original issue: Microsoft/Access2Justice#866_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
