### ISSUE TITLE
Default map zoom level on org detail page too close

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#711]
_From @aroubin on December 5, 2018 5:23_

On organization detail page, default zoom level for map is too close. Need to zoom out a bit more to see cross streets. 

_Copied from original issue: Microsoft/Access2Justice#867_

**Comment by svasylenko** [comment]
If I understood the issue correctly - default map is zoomed out. Hence Verified.

![image](https://user-images.githubusercontent.com/46557859/51490945-84742100-1db5-11e9-909e-ffa018312c13.png)

**Comment by KellyeDC-zz** [comment]
Issue resolved
