### ISSUE TITLE
As State Admin, I need to edit privacy policy content so that users in my state understand what information about them is collected and how it is being used.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#72]
_From @czdiana2321 on May 21, 2018 21:32_

USER->Profile

Acceptance Criteria:

1. State Admin User is able to view the privacy policy page.
2. State Admin User is able to make content changes manually to the privacy policy and save the changes.
3. The system is able to display the updated privacy policy on the Privacy Policy page.

_Copied from original issue: Microsoft/Access2Justice#90_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
