### ISSUE TITLE
As Portal User, I want to be able to go back to previous question on curated experience

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#721]
_From @aroubin on December 6, 2018 21:12_

Sometimes users will want to go back to previous question in curated experience so that they can change some of their responses. 

_Copied from original issue: Microsoft/Access2Justice#878_

**Comment by breeglej** [comment]
I agree that this needs to be in sprint soon.  Users need a back button while in the curated experience.

**Comment by KellyeDC-zz** [comment]
Back button in CE or GA is in the current sprint.  The team is working on this now.

Thanks,

Kellye Bennett
Legal Navigator Project Manager
Legal Services Corporation
[cid:image001.jpg@01D4EF9B.72CF61F0]
Office of Information Technology
3333 K Street, NW
Washington, DC 20007
P: 202.295.1569
E: bennettk@lsc.gov<mailto:bennettk@lsc.gov>

**Comment by lbirdpew** [comment]
Does this include a back button for when I click out of the site from the action plan?

**Comment by KellyeDC-zz** [comment]
The desired behavior is for a new window to load when user clicks on an external link, which would in theory maintain the step the user is in within the Guided Assist (CE).

**Comment by lbirdpew** [comment]
yeah, that's not currently happening.  I just tried the domestic violence flow in AK

**Comment by KellyeDC-zz** [comment]
@lbirdpew This issue is "In Progress" and the development team is currently working on the fix in the development environment for this sprint.  Once resolved, it will be assigned to me for testing.  If you'd like to be included in testing, please let me know.  Once the fix is completed, the new code will be migrated to the stage environment and available for other stakeholders to review.  The sprint ends on April 16th. Hope this helps.

**Comment by lbirdpew** [comment]
No worries, i was just curious if there was another issue for it.

**Comment by KellyeDC-zz** [comment]
<img width="487" alt="Issue 721 Back Button in GA" src="https://user-images.githubusercontent.com/45771252/59602646-3f8ab700-90d5-11e9-93cf-0533c5ef36a1.PNG">

**Comment by KellyeDC-zz** [comment]
Back Button added to Guided Assistant - Ready for PO review

**Comment by grawdon** [comment]
@KellyeDC The Back button works, but I lose my previous answers. Is this the desired behavior?

**Comment by KellyeDC-zz** [comment]
@grawdon This is not the overall desired behavior, however, this user story is only for implementing the back button feature.  The save interview answers along the way feature is a separate issue.
