### ISSUE TITLE
Browser Tab image is not visible in incognito mode of chrome 

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#724]
_From @turpu-rakesh on December 7, 2018 4:18_

Not able to see letter L in incognito mode. please find below screenshot for the same.

![image](https://user-images.githubusercontent.com/38064129/49627477-104c0c80-fa05-11e8-8959-5e7314f4bd40.png)

_Copied from original issue: Microsoft/Access2Justice#883_

**Comment by KellyeDC-zz** [comment]
@svasylenko Serhii, I am not sure what the defect is, specifically Letter L.

**Comment by breeglej** [comment]
@KellyeDC - I don’t understand this issue.

**Comment by KellyeDC-zz** [comment]
@svasylenko Please explain this issue for us.

**Comment by grawdon** [comment]
@KellyeDC I tested this and it displayed fine in Incognito mode in Chrome.

![image](https://user-images.githubusercontent.com/46725623/57228766-32f54800-6fda-11e9-850a-e4e7952a40b0.png)
