### ISSUE TITLE
As Portal User, I want to save my personalized action plan so that I can come back to it later. 

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#73]
_From @czdiana2321 on May 21, 2018 21:34_

USER-> Profile

Acceptance Criteria:
1. Portal User is able to create a personalized plan using the Guided Assistant
2. Portal User is able to save the personalized plan by logging into the account.
3. Portal User is able to navigate to profile and saved personalized plan listed.
4. Portal User is able to review the saved personalized plan.

_Copied from original issue: Microsoft/Access2Justice#91_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh
