### ISSUE TITLE
Create dev/stage/prod resource groups in LSC's Azure subscription

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#730]
_From @aroubin on December 7, 2018 23:41_

Create resources in LSC's Azure subscription for deployment of A2J dev/stage/prod sites.

_Copied from original issue: Microsoft/Access2Justice#890_

**Comment by KellyeDC-zz** [comment]
All three environments in place. Dev/Stage/Prod.  Currently, PROD is not available until soft launch.  However, it will be maintained and updated until then.
