### ISSUE TITLE
legalnav.org DNS changes

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#731]
_From @aroubin on December 7, 2018 23:43_

List of domains to create:

Prod
--------
web: legalnav.org (done)
      www.legalnav.org --> CNAME legalnav.org (done)

api: api.legalnav.org

integration: integration.legalnav.org

Stage
-------
web: stage.legalnav.org
      
api: api.stage.legalnav.org

integration: integration.stage.legalnav.org

Dev
-----
web: dev.legalnav.org
      
api: api.dev.legalnav.org

integration: integration.dev.legalnav.org

_Copied from original issue: Microsoft/Access2Justice#891_

**Comment by LegalSvcsCorp** [comment]
Etienne completed updates to DNS for legalnav.org
