### ISSUE TITLE
Upload legalnav.org wildcard cert to Azure web / API apps

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#732]
_From @aroubin on December 7, 2018 23:44_

Upload wildcard org for *.legalnav.org to API and web apps (dev/stage/prod) in LSC's Azure subscription 

_Copied from original issue: Microsoft/Access2Justice#892_

**Comment by LegalSvcsCorp** [comment]
Andrew Roubin and Etienne Riggins completed.
