### ISSUE TITLE
Create MS Account apps for legalnav.org

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#734]
_From @aroubin on December 7, 2018 23:49_

for each of the web and API apps (dev/stage/web, 6 total), create MS Account application in MS Developer Center using legalnav's admin email address. Apps can't be shared between multiple email accounts, so a shared account needs to be used for this purpose. 

_Copied from original issue: Microsoft/Access2Justice#894_

**Comment by LegalSvcsCorp** [comment]
Andrew Roubin worked with Etienne Riggins to complete this task.
