### ISSUE TITLE
Selection of account is not proper while login in Mobile Browser

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#736]
_From @charmila-c on December 10, 2018 10:32_

_Copied from original issue: Microsoft/Access2Justice#897_

**Comment by aroubin** [comment]
_From @yfzwinnie on December 10, 2018 16:48_

@charmila-c please include screenshots

**Comment by KellyeDC-zz** [comment]
Successful login using mobile browser
