### ISSUE TITLE
Save to profile/Share/Download options in personalized plan page are displayed only at bottom of the page after organizations in mobile browser and Print option is not available for personalized plan page in mobile browser

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#738]
_From @charmila-c on December 10, 2018 10:36_

![image](https://user-images.githubusercontent.com/38064775/49727327-f07f4780-fc95-11e8-9464-f940fdd74bb8.png)

_Copied from original issue: Microsoft/Access2Justice#899_

**Comment by aroubin** [comment]
_From @yfzwinnie on December 10, 2018 16:45_

The placement of the user actions are in compliance with the Fellswoop design. Will add the print button to mobile view.

![image](https://user-images.githubusercontent.com/20545930/49747277-f0605700-fc57-11e8-91e1-5fc2c4c572b3.png)

**Comment by svasylenko** [comment]
Verified

![image](https://user-images.githubusercontent.com/46557859/51620330-c9759000-1f3a-11e9-8bac-48f2ff2638b8.png)
