### ISSUE TITLE
In Search Results, on selecting sort by, A-Z and going to second page, the search results are not getting sorted properly- happens on selecting any filter(videos/ Forms/ Organizations) even in 1st page.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#739]
_From @charmila-c on December 10, 2018 10:40_

_Copied from original issue: Microsoft/Access2Justice#900_

**Comment by KellyeDC-zz** [comment]
@grawdon Do we need to update this to prioritize display based on relevance?  Do we provide this option to filter alphabetically?

**Comment by grawdon** [comment]
@KellyeDC I think displaying by relevance negates the need to do this work, although we did decide they should be alphabetical within the relevance layer. But I think we should get it sorting by relevance first and then see if there is an issue within those layers.
