### ISSUE TITLE
As Portal User, I need to access the portal's Privacy Policy so that I can understand what information is being collected as I use the portal (without creating a profile), how it is being secured, and how it will be used by the portal. 

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#74]
_From @czdiana2321 on May 21, 2018 21:36_

USER->Profile

Acceptance Criteria:

1. Portal User is able to access the Privacy Policy page in the portal.
2. Portal User is able to view and understand the Privacy Policy.

_Copied from original issue: Microsoft/Access2Justice#92_

**Comment by yfzwinnie** [comment]
Completed as part of MVP.

**Comment by grawdon** [comment]
User can review privacy policy. Issue ready to close.
