### ISSUE TITLE
Displaying console error while accessing few videos

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#741]
_From @charmila-c on December 10, 2018 10:44_

•	While accessing few videos, facing below error -->Hawaii -> Topics/Family/Adoption, Guardianship, and POA ->Videos (select below video)  
From <http://localhost:5150/topics/9c9a59cc-34ac-4a6f-80c4-90ac041abba7> 
![image](https://user-images.githubusercontent.com/38064775/49727639-bf534700-fc96-11e8-8de3-904c582e7ef9.png)

_Copied from original issue: Microsoft/Access2Justice#903_

**Comment by svasylenko** [comment]
Could not reproduce.

![image](https://user-images.githubusercontent.com/46557859/52577092-12c64a80-2e2a-11e9-98c0-ba6e58e2dede.png)
