### ISSUE TITLE
Create a new endpoint to filter resources by state and topic name

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#750]
_From @alaatadmori on December 12, 2018 20:51_

Based on a discussion with the A2J Author team we are to provide a new endpoint that returns a list of resources by state and topic name:
/api/topics-resources/resource?state=Ak&topicName=Divorce

They will use this to display the relevant resources when authoring a personalized plan.

_Copied from original issue: Microsoft/Access2Justice#913_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
