### ISSUE TITLE
Create api endpoint for Guided Assistant Privacy Disclaimer static content

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#751]
_From @yfzwinnie on December 12, 2018 22:41_

The following data should be coming from the database:

![image](https://user-images.githubusercontent.com/20545930/49903446-1cc4d080-fe1c-11e8-94f1-673a640ab6d1.png)

_Copied from original issue: Microsoft/Access2Justice#915_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
