### ISSUE TITLE
Site search does not return LegalNav articles

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#756]
_From @aroubin on December 13, 2018 22:32_

Articles defined in LegalNav site do not get included in site search results. Only Bing search results are displayed. 

Repro: in the search bar, type "Registering a custody or support order"

Expected results: article shows up at the top of the search results

Actual: only Bing search results from the web are shown.

_Copied from original issue: Microsoft/Access2Justice#920_

**Comment by aroubin** [comment]
_From @alaatadmori on December 18, 2018 23:56_

I checked the behavior of the search engine and debugged the code to double check there was no issues - all checked fine. The reason why no article was surfaced by the search engine when searching for "Registering a custody or support order" is because the article was entered to the db but not associated with a topic. The search engine doesn't perform a text search over the db, instead, it hits LUIS engine to get the 'intent' of the user and based on the intent it searches the 'Topics' collection to see if the db has any 'Resources' for that particular topic, if yes it returns all the Resources it finds.

In the case of this article "Registering a custody or support order", LUIS is returning 'Child Support' as the intent. The db has the topic 'Child Support' and it has many Resources associated with it but this article was not one of them.

To resolve this, the article must be associated with the 'Child Support' topic.

**Comment by svasylenko** [comment]
![image](https://user-images.githubusercontent.com/46557859/51377060-94b8a180-1b12-11e9-9c2c-35f90cc8e908.png)

**Comment by KellyeDC-zz** [comment]
Need to revisit with SMEs to confirm. @grawdon

**Comment by grawdon** [comment]
@KellyeDC The explanation sounds feasible. I can't see the database to confirm. We should be sure the SMEs know to do this so their resources are returned in search results.

**Comment by grawdon** [comment]
The search feature would not work for me today. I tried four different terms and each time all I got was a spinning "loading" wheel. So I couldn't see if articles were returned or not since nothing was.

**Comment by grawdon** [comment]
Yes, articles were showing up in the searches.
