### ISSUE TITLE
Duplicate values in resource filter dropdown in search page

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#758]
_From @turpu-rakesh on December 14, 2018 6:33_

issue 1 : seeing resource type All twice one is having resource count and other is not having resource count.
issue 2 : resource type drop down values are going out and overlapping on the page content. Ex : **Essential Readings**

![image](https://user-images.githubusercontent.com/38064129/49987068-0fccec00-ff98-11e8-9663-cf87e902cfaf.png)

_Copied from original issue: Microsoft/Access2Justice#922_

**Comment by oleksandr-bytsiuk-gloriumtech** [comment]
Fixed in UI update.
