### ISSUE TITLE
As a portal User ,  I want to be able to share my information (Action Plan) with another person/party that I trust and can help me with my situation securely.   I should be also able to stop sharing my information whenever I want.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#76]
_From @czdiana2321 on May 21, 2018 21:41_

USER-> Profile

Acceptance Criteria:

1. The Portal User is able to share information by entering email address in the recipient email address and creating a custom message.
2. The system is able to provide an option to create a secured link and send it to another user.
3. The system is able to generate an email through a web form.

_Copied from original issue: Microsoft/Access2Justice#94_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh
