### ISSUE TITLE
Feature/792 save topics for later

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#763]
_From @charmila-c on December 17, 2018 17:4_

#792 

_Copied from original issue: Microsoft/Access2Justice/pull/930_

**Comment by aroubin** [comment]
_From @charmila-c on December 19, 2018 6:38_

Hi Alaa,

As discussed in call, I have tested the references for the method, FindItemsWhereInClauseAsync and it is working fine. Resolved conflicts after merging with latest develop

**Comment by aroubin** [comment]
_From @charmila-c on December 21, 2018 4:17_

Hi Winnie, as discussed it is a data problem and I have added the topic 'Identity' in Topics Collection again. It is working fine.

**Comment by aroubin** [comment]
_From @yfzwinnie on December 27, 2018 14:50_

Charmila, currently when the resource doesn't exist, the spinner shows indefinitely. In the meantime, can we  hide the spinner and just show a warning saying "This resource does not exist" for now?

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
