### ISSUE TITLE
Upload v1 of white listed sites to Legal Nav.  

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#764]
_From @shandang on December 17, 2018 19:29_

[LSC whitelisted sites (v1).xlsx](https://github.com/Microsoft/Access2Justice/files/2687578/LSC.whitelisted.sites.v1.xlsx)

_Copied from original issue: Microsoft/Access2Justice#931_

**Comment by aroubin** [comment]
_From @alaatadmori on December 18, 2018 18:6_

Sateesh uploaded the list.

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
