### ISSUE TITLE
Feature/530 adaptor design

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#765]
_From @alaatadmori on December 18, 2018 18:10_

_Copied from original issue: Microsoft/Access2Justice/pull/932_

**Comment by aroubin** [comment]
_From @msftclas on December 18, 2018 18:10_

[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/Microsoft/Access2Justice?pullRequest=932) <br/>All CLA requirements met.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
