### ISSUE TITLE
Add a property to organization resource type to indicate if that organization supports onboarding

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#766]
_From @yfzwinnie on December 18, 2018 22:22_

Add property to indicate if organization supports onboarding and create a mock organization that is currently supporting this for the demo.

_Copied from original issue: Microsoft/Access2Justice#933_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh.
