### ISSUE TITLE
As a portal user I should be able to access Information (Action Plan) shared with me by other portal users securely.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#77]
_From @czdiana2321 on May 21, 2018 21:43_

USER-> Profile

Acceptance Criteria:

1. Portal User is able to receive an email with a link
2. Portal User is able to click on this link from the email client.
3. The Portal User is taken to the Portal and prompted to login.
4. Once logged in the user is able to see and access the information shared by other portal user.

_Copied from original issue: Microsoft/Access2Justice#95_

**Comment by svasylenko** [comment]
New definition of task content:

To create section Notifications here (Account->My Plan)

![image](https://user-images.githubusercontent.com/46557859/54775888-976d6b00-4c17-11e9-9446-b4bf3a611383.png)


To add text block here with e-mail and Share button

![image](https://user-images.githubusercontent.com/46557859/54775718-33e33d80-4c17-11e9-8dd2-3ad89b4cf172.png)

and statement: Please enter Legal Navigator's existing user e-mail to share: 

After pressing this button, content to be seen in that user's Notification pane (looks similar to My Saved Resources pane).

**Comment by svasylenko** [comment]
@KellyeDC please review written above

**Comment by KellyeDC-zz** [comment]
Unable to receive link to action plan as registered user.

**Comment by breeglej** [comment]
@KellyeDC -  I agree that this is not done.  We need to get this fixed.  It’s also in the defect log.

**Comment by grawdon** [comment]
@KellyeDC Can you share an action plan with me so we can test this? grawdon@lsc.gov.

**Comment by KellyeDC-zz** [comment]
Please use the DEV environment for this one as well.

Kellye Bennett
Legal Navigator Project Manager
Legal Services Corporation
[cid:image001.jpg@01D504CB.438C0660]
Office of Information Technology
3333 K Street, NW
Washington, DC 20007
P: 202.295.1569
E: bennettk@lsc.gov<mailto:bennettk@lsc.gov>

**Comment by grawdon** [comment]
When I save the plan and share it, I don't get an email and pasting the link into the browser takes me to a blank page.

**Comment by KellyeDC-zz** [comment]
Feature is behaving as expected.  @breeglej  and @grawdon , it only allows sharing for registered users.  We need to consider the impact an design for non-registered users.

**Comment by Olgaivchenko** [comment]
@KellyeDC 
Hello Kellye,
please provide us with the vision of expected behaviour ( **for non-registered users**)

**Comment by grawdon** [comment]
@KellyeDC Share was not working between my accounts. I'm going to share something with you to see if it is working.

**Comment by grawdon** [comment]
Kellye and I were able to share. This is working.
