### ISSUE TITLE
Bug 845 Partial Fix & Bug# 867 functionality implemented

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#777]
_From @vennasr on December 26, 2018 10:52_

Bug #845 Partial Fix - Removed experimental branch from the Bing map reference which is throwing multiple console errors. 
2nd issue mentioned in the bug is fixed with this fix.

Bug #867 - Default map zoom level on org detail page too close #867 - Functionality is fixed

_Copied from original issue: Microsoft/Access2Justice/pull/945_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
