### ISSUE TITLE
Feature/data import tool changes

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#778]
_From @vennasr on December 27, 2018 8:15_

1) Removed the CSVImporter project  - Duplicate code same as DataImporter hence removed
2) Added solution file outside the CSVImporter project
3) Updated the DataImporter Project file and removed the CSVImporter references.

_Copied from original issue: Microsoft/Access2Justice/pull/946_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
