### ISSUE TITLE
As a Portal User, I want to be able to remove resources from the list of saved resources so that I will only have the relevant resources I need.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#78]
_From @czdiana2321 on May 21, 2018 21:45_

USER-> Profile

Acceptance Criteria:

1. User is able to remove resource from the list of saved resources.
2. The system is able to provide option for removal of resource/s from the list of saved resources.

_Copied from original issue: Microsoft/Access2Justice#96_

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh
