### ISSUE TITLE
Feature/bug 912

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#780]
_From @nehaljoshi212 on December 27, 2018 16:39_

fixed bug 
#912 

_Copied from original issue: Microsoft/Access2Justice/pull/948_

**Comment by aroubin** [comment]
_From @nehaljoshi212 on December 28, 2018 9:35_

Hi Alaa/Winnie,

I have merged develop to resolve conflicts.
Followed steps u asked regarding build and test. Did not see any deviation.
Please review. Nice working with you all!! 👍 

thanks,
Nehal

**Comment by aroubin** [comment]
_From @nehaljoshi212 on December 28, 2018 9:54_

Hi Alaa/Winnie,

Merged again from develop to resolve conflicts.
Followed steps u asked regarding build and test. Did not see any deviation.
Please review. Nice working with you all!! 👍

thanks,
Nehal

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
