### ISSUE TITLE
Feature/49 display bing map in portal

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#79]
_From @charmila-c on May 22, 2018 10:7_

This pull request include the display of bing map in the portal where user can search for a location and update the searched location. 

This does not include unit testing.

_Copied from original issue: Microsoft/Access2Justice/pull/97_

**Comment by aroubin** [comment]
_From @msftclas on May 22, 2018 10:7_

[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/Microsoft/Access2Justice?pullRequest=97) <br/>All CLA requirements met.

**Comment by aroubin** [comment]
_From @charmila-c on May 23, 2018 9:8_

Closing this request and will raise a new request as it include other branches code as well.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
