### ISSUE TITLE
Bing map 'uncaught invalid usage" console error

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#790]
_From @yfzwinnie on January 2, 2019 19:34_

 This error appears whenever you update your location and when you filter on the search result page (home page, search result filtering):
![image](https://user-images.githubusercontent.com/20545930/49188487-cd60a980-f31f-11e8-8f7a-39dd12cf1726.png)

_Copied from original issue: Microsoft/Access2Justice#958_

**Comment by svasylenko** [comment]
We could not reproduce that. For remaining error new bug issue is created #852.

![image](https://user-images.githubusercontent.com/46557859/53009634-a01a2800-3444-11e9-8f1e-393bd918486a.png)
