### ISSUE TITLE
Code chages related to the following:

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#8]
_From @raghunath2711 on March 30, 2018 21:59_

1.update the uploader to upload all content types (video, proess steps, and QA)
2. Incorporated Language translation web job and hooked it with uploader ui , to enable users to trigger the translation job.
3. Updated the web api Rest services to handle languagecode as  a parameter and enable translation for the response payload

_Copied from original issue: Microsoft/Access2Justice/pull/8_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
