### ISSUE TITLE
Feature/49 display bing map in a2j portal

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#80]
_From @charmila-c on May 23, 2018 9:13_

This pull request include the display of bing map in the portal where user can search for a location and update the searched location.
This does not include unit testing.

_Copied from original issue: Microsoft/Access2Justice/pull/98_

**Comment by aroubin** [comment]
_From @charmila-c on May 28, 2018 7:6_

Closing this Pull Request as I have raised it by mistake to master branch. Will raise a new Pull Request along with the fix for bug raised by Winnie.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
