### ISSUE TITLE
Feature/front end cleanup

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#800]
_From @yfzwinnie on January 11, 2019 15:43_

Clean up front end code to ensure consistency and better formatting based on best practice:
- deleted unnecessary whitespace
- deleted unused imports
- format import order
- format all ts, html, and css files by adding line breaks where needed
- changed all quotes to be double quote instead of single
- adjusted user-action (save, share, print, download) layout for mobile vs tablet vs desktop version
- got rid of spacing when certain information is not included for resource (i.e. spacing when there are no map results, spacing when there are no overviews on subtopic page)
- deleted old images and sample json files
- moved services and pipes to new folders

_Copied from original issue: Microsoft/Access2Justice/pull/968_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
