### ISSUE TITLE
Allow portal admins to onboard a new state if it doesn't already have contents.

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#802]
_From @yfzwinnie on January 11, 2019 20:58_

For this task we need:
- an endpoint that returns a list of states that already have contents (i.e. AK, HI, Default);
- an endpoint where on the front end we can send the state code as the parameter and the backend will create all the default pages (privacy promise, home, about etc.) in the database for that state.  This state will now be included in the 1st endpoint in which now the portal admin can go in and customize the pages for that new state.

_Copied from original issue: Microsoft/Access2Justice#970_

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
