### ISSUE TITLE
Feature/792 save topics for later

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#806]
_From @charmila-c on December 17, 2018 16:58_

#792 

_Copied from original issue: Microsoft/Access2Justice/pull/929_

**Comment by aroubin** [comment]
_From @charmila-c on December 17, 2018 17:0_

Closing this Pull Request and raising a new Pull Request as I have raised this by mistake to master branch rather than develop branch

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
