### ISSUE TITLE
Login to a2j does not work properly

### ISSUE THREAD

**Issue by svasylenko** [LSCOIT/LegalNavigator#809]
I have to login twice before system finally recognize me as a user. Please see attached video.

[Jan 18, 2019 4_02 PM (1).zip](https://github.com/LSCOIT/LegalNavigator/files/2773222/Jan.18.2019.4_02.PM.1.zip)

**Comment by aroubin** [comment]
Apps in MS dev portal are configured with httpS URLs as site and return URLs. So this will happen if you hit the site with http. In the new LSC subscription, we configured an option to force SSL on all requests so this behavior can be avoided.

**Comment by svasylenko** [comment]
Fixed by forcing SSL usage.
