### ISSUE TITLE
Fit & Finish Issue #80: If there are a lot of forms for a topic, put them in alpha order for faster scanning #925

### ISSUE THREAD

**Issue by Caleb-Siebeneck** [LSCOIT/LegalNavigator#827]
If there are a lot of forms for a topic, put them in alpha order for faster scanning - 
makes for a beter UX, helps improve fndability if I know the frst leter of the form. @amitabhm21

**Comment by svasylenko** [comment]
Topics & Resources and others: if Forms are presented there - sort them A->Z by name.

![image](https://user-images.githubusercontent.com/46557859/54773573-8a01b200-4c12-11e9-9575-be3cc8ae0a43.png)

**Comment by KellyeDC-zz** [comment]
@grawdon I have reviewed this update.  I think we are working on changing this to rank.

**Comment by grawdon** [comment]
Forms displayed were in alphabetical order.
