### ISSUE TITLE
Template for curated experience display

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#85]
_From @charmila-c on May 25, 2018 11:41_

Includes template for Curated Experience search results display with mock data. #67 

_Copied from original issue: Microsoft/Access2Justice/pull/105_

**Comment by aroubin** [comment]
_From @turpu-rakesh on June 1, 2018 11:0_

@yfzwinnie Fixed code review comments. please have a look and provide comments.

Thanks,
Rakesh

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
