### ISSUE TITLE
Add NSMI v2 codes to Content Development Matrix

### ISSUE THREAD

**Issue by LegalSvcsCorp** [LSCOIT/LegalNavigator#863]
Add NSMI v2 codes to Content Development Matrix

**Comment by LegalSvcsCorp** [comment]
ON HOLD - Requirements Spike

**Comment by KellyeDC-zz** [comment]
https://nsmi.lsntap.org/browse-v2

**Comment by svasylenko** [comment]
@KellyeDC we will add for new content but what to do with already existing? Please suggest.

**Comment by KellyeDC-zz** [comment]
@svasylenko this task is assigned to me to complete for the state content matrix per the updated NSMI v2 Codes.  The matrix was developed earlier in the year by myself and state stakeholders.  There's nothing for the dev team to do on this issue.
