### ISSUE TITLE
Verify that existing content for Alaska has appropriate NSMI v2 code tagged

### ISSUE THREAD

**Issue by LegalSvcsCorp** [LSCOIT/LegalNavigator#864]
Verify that existing content for Alaska has appropriate NSMI v2 code mapped

**Comment by LegalSvcsCorp** [comment]
ON HOLD - Requirements Spike

**Comment by KellyeDC-zz** [comment]
Reference:- https://nsmi.lsntap.org/browse-v2

**Comment by KellyeDC-zz** [comment]
Moving task to Smartsheet - Objectives
