### ISSUE TITLE
Verify that existing content for Hawaii has appropriate NSMI v2 code tagged

### ISSUE THREAD

**Issue by LegalSvcsCorp** [LSCOIT/LegalNavigator#865]
Verify that existing content for Hawaii has appropriate NSMI v2 code mapped

**Comment by LegalSvcsCorp** [comment]
ON HOLD - Requirements Spike

**Comment by KellyeDC-zz** [comment]
Link to NSMI v2 codes: https://nsmi.lsntap.org/browse-v2

**Comment by KellyeDC-zz** [comment]
Moving task to Smartsheet - Objectives
