### ISSUE TITLE
Refactor Cosmos DB code to optimize querying for dynamic documents

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#88]
_From @alaatadmori on May 29, 2018 22:7_

We are currently using string manipulation to query for many-to-many topics/resources matches. Consider using a different way, maybe using a stored proc (cross-collection stored procs are not supported yet by cosmos but once they will be available we could make use of it).

_Copied from original issue: Microsoft/Access2Justice#110_

**Comment by aroubin** [comment]
_From @alaatadmori on June 13, 2018 6:16_

Code reviewed with Andrew.

**Comment by yfzwinnie** [comment]
Completed as part of MVP and closed by Amitabh
