### ISSUE TITLE
Additional readings should be UNDER articles (they are additional..) 

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#898]
Additional readings should be UNDER articles (they are additional..) 

Issue submitted by Suzanne (SME)

**Comment by breeglej** [comment]
@KellyeDC - Agree.  Please find out how difficult this would be.

**Comment by KellyeDC-zz** [comment]
"Additional Readings" has been appropriately moved to the end of the resources results page.
<img width="912" alt="Additional REadings Moved to end of page DEV" src="https://user-images.githubusercontent.com/45771252/57032625-daf4c500-6c18-11e9-8044-7242b94ff6c4.PNG">
<img width="855" alt="Additional Readings STAGE" src="https://user-images.githubusercontent.com/45771252/57032630-dd571f00-6c18-11e9-86dd-cac57761f524.PNG">

**Comment by grawdon** [comment]
@KellyeDC It looks to me like Additional Readings are still coming above Articles. But in my example below, the "readings" are more in the nature of "topics". We should discuss this on a call to be sure what change we need to make, if any.

![image](https://user-images.githubusercontent.com/46725623/57231750-c6317c00-6fe0-11e9-8643-f117578280f0.png)

**Comment by grawdon** [comment]
@KellyeDC I verified this worked in dev.
