### ISSUE TITLE
created 4 main projects Web, Api, Common, and Tests. All projects are…

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#9]
_From @alaatadmori on April 19, 2018 21:4_

Created 4 main projects Web, Api, Common, and Tests. All projects are still bear bone with no custom code added yet.

_Copied from original issue: Microsoft/Access2Justice/pull/9_

**Comment by aroubin** [comment]
_From @msftclas on April 19, 2018 21:4_

[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/Microsoft/Access2Justice?pullRequest=9) <br/>All CLA requirements met.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
