### ISSUE TITLE
Feature/68 69 build template for web results and resources

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#90]
_From @yfzwinnie on May 30, 2018 19:32_

This pull request contains the following tasks:
- #68 Build the template for resources
- #69 Build the template for web results
- #19 Create UI for search

_Copied from original issue: Microsoft/Access2Justice/pull/113_

**Comment by aroubin** [comment]
_From @yfzwinnie on May 30, 2018 19:35_

Closing this pull request. Just realized this is a duplicate of #112.

**Comment by LegalSvcsCorp** [comment]
Move to MVP-Microsoft
