### ISSUE TITLE
Add Alaska Courts Systems to Alaska view of Legal Navigator

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#905]
Background: You had wondered if Alaska Court System could be added to bottom of the first page where it talks about “information you can trust” and lists LSC and probono.net.  As mentioned in 11, below, Alaska Court System is currently listed when a person gets a PAP.  It may be that is the place they plan to list state partners.

Issue submitted by Stacey Marz (AK)

See the output for Hawaii Action Plan.

**Comment by breeglej** [comment]
@KellyeDC - If we can add this just to Alaska, we should do it.  Please find out if that’s possible.

**Comment by svasylenko** [comment]
@breeglej Jada, could you please suggest shall we add Hawaii Court System logo as well?

**Comment by breeglej** [comment]
@svasylenko - I didn't see an answer to my question.  Can this logo be added only to Alaska personal action plans?

**Comment by svasylenko** [comment]
@breeglej yes, Jada - this could be added to Alaska only.

**Comment by breeglej** [comment]
@KellyeDC - This is a question for you.  Please find out from Nalani if she wants a logo added to the Hawaii PAPs.  It wouldn't be the courts logo, but maybe Nalani's logo.

**Comment by KellyeDC-zz** [comment]
@breeglej I think the Hawaii logo is already on the personalized action plan.  It is available but appears to have a defect when downloaded @svasylenko

**Comment by KellyeDC-zz** [comment]
The logo is already there on the HI side.  It is missing from the AK side.

Regards,

KB

Kellye Bennett
Legal Navigator Project Manager
Legal Services Corporation
[cid:image001.jpg@01D4FB73.EA337A40]
Office of Information Technology
3333 K Street, NW
Washington, DC 20007
P: 202.295.1569
E: bennettk@lsc.gov<mailto:bennettk@lsc.gov>

**Comment by breeglej** [comment]
@KellyeDC - Thanks!  Got it.

**Comment by KellyeDC-zz** [comment]
@svasylenko How do we navigate to this screen?

**Comment by grawdon** [comment]
@KellyeDC Is this resolved with the addition of the AK state courts logo now? I don't think we want the AK to show up on the HI pages.

**Comment by grawdon** [comment]
@KellyeDC I don't see any logos on the home page or on the About page when you click Learn More in the Information You Can Trust Section. If this the design we decided upon?

**Comment by KellyeDC-zz** [comment]
Agreed.  I will return to DEV.  I recall seeing this during the sprint review but was unable to reproduce.

**Comment by Olgaivchenko** [comment]
Done in Sprint 11. Move to Ready fore Review

**Comment by KellyeDC-zz** [comment]
It was done, but it is no longer displaying. @svasylenko

**Comment by yevhenobertas** [comment]
Need more information: "It was done, but it is no longer displaying".

**Comment by KellyeDC-zz** [comment]
Demo provided today.  It is displaying in DEV, not in Stage.

Kellye Bennett
Legal Navigator Project Manager
Legal Services Corporation
_____________________________________________________________________
Office of Information Technology
3333 K Street, NW
Washington, DC 20007
P: 202.295.1569
M: 703.889.7288
E: bennettk@lsc.gov
________________________________

**Comment by svasylenko** [comment]
@KellyeDC are you referring to this logo? Or it should be somewhere else?

![image](https://user-images.githubusercontent.com/46557859/66640870-62138380-ec22-11e9-8dba-5adedf587468.png)

**Comment by grawdon** [comment]
@KellyeDC Where did they want the logo? Right now it is by itself in a section above information you can trust. And none of the information buttons go anywhere. I get a 404 error. 

![image](https://user-images.githubusercontent.com/46725623/72189006-5a01e600-33c1-11ea-9f78-51dfdfdab370.png)

**Comment by grawdon** [comment]
@KellyeDC The Alaska Court logo shows up on their page. For Hawaii, it only says: Hawaii community member. Is that a place holder? If so, we need to see what they want to go there.

**Comment by grawdon** [comment]
The Alaska court system logo and quote have been added.
