### ISSUE TITLE
Save Multiple Iterations of an Individual's Guided Assist

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#907]
Background: 
I think it would be a big improvement if people did NOT lose their PAP if they answered the questions of a curated experience a second time.  That would allow a person to end, but get more information later, and would resolve the “looping” problem.  The other option is moving to “child 2” categories and multiple curated experiences, but that would also mean staring over on the divorce section, but maybe that’s the best option in the long run.  But we would want to spend a fair bit of time thinking through all the “child 2” options and whether they covered everything and were broad enough to stand alone.  Even if we did that, I think being able to answer more than once is beneficial.  The reason for not allowing it was to prevent the PAPs from getting too long.  An alternate solution would be to allow the user to delete items from their PAP.  

Issue Submitted by Stacey Marz (AK)

**Comment by breeglej** [comment]
@KellyeDC - I think this is the question we’ve answering over the last couple days.  We will allow states to write curated experiences at child level 2.  I don’t think this belongs in defects.

**Comment by KellyeDC** [comment]
@breeglej Once the development plan for resolving the authoring and NLP disconnect, this issue can be closed.

**Comment by grawdon** [comment]
@KellyeDC Agreed. I would close this.
