### ISSUE TITLE
Order Change in Personalized Plan -Due to A2J Author

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#912]
The PAP information does not come up in the order of the person’s answers – it may be the order of the PAPs in the original A2J program, but I’m not sure.  This increased the confusion with calling the different topics “steps.”

Issue submitted by Stacey Marz (AK).  Confirmed issue with Nalani Kaina (HI).  

Work with  A2J Author team to determine resolution

**Comment by breeglej** [comment]
@KellyeDC - I think we should mark this as high priority.

**Comment by breeglej** [comment]
@KellyeDC  - Can we find out how it's done today (i.e. how does it get in the order)? I think we need more information.

**Comment by grawdon** [comment]
Coming up in the order of the persons answers may not be the desired result. We need to discuss this as a design issue and see if it can be ordered in A2J Author.

**Comment by grawdon** [comment]
@KellyeDC This would be good to discuss with Jeannie too.
