### ISSUE TITLE
Additional Readings for Personalized Action Plan

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#914]
When you get your PAP, on the side it throws in “Additional Readings” which may or may not be relevant (in part b/c we lumped so much under “divorce”).  When you print a PAP, it shows up at the bottom.  After all we gave them in the PAP this doesn’t seem necessary and may be redundant or inappropriate.  If the goal is tailored PAPs, throwing these in defeats that goal.

**Comment by breeglej** [comment]
@KellyeDC - This seems to be a duplicate to #918
