### ISSUE TITLE
In Guided Assist, When suggesting topics, use Singular/Plural when applicable

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#920]
Background: When you go to Guided Assistant and plug in a topic, it brings you to the page to start the experience.  At the bottom it says, “You may also be interested in the following topic:”. Then it lists 3 topics (or that’s what I got).  First (and less importantly) if there are more than 1 topics listed, it should say “topics” not “topic.”  More importantly, the topics I got weren’t related to what I had written I was interested in.  

NOTE: (I included you in an e-mail to Shandan, Alaa, and Winnie that included the 3 sentences of this point.)

Issue submitted by Jeannie Sato (AK)

**Comment by breeglej** [comment]
@KellyeDC  - The topics not being related is a function of the NLP lack of training.  I don't think there is anything to fix there and we'll have to wait for NLP to mature.  On the singular/plural issue, we should just fix if it is straightforward and doesn't take much developer time.

**Comment by breeglej** [comment]
@KellyeDC - Let's fix this with a Topic(s)

**Comment by KellyeDC-zz** [comment]
Logic updated to display **topics** when multiple suggestions are offered and **topic** when a singe suggestion is offered.
<img width="773" alt="#920 Topic Singular with multiple suggetions STAGE" src="https://user-images.githubusercontent.com/45771252/57032328-19d64b00-6c18-11e9-8d82-513179c8c8da.PNG">
<img width="786" alt="#920 Topics Plural when multiple topics are suggested DEV" src="https://user-images.githubusercontent.com/45771252/57032331-1c38a500-6c18-11e9-83b3-2199b3d2fbb2.PNG">

**Comment by grawdon** [comment]
@KellyeDC I thought we said to fix with "topic(s)". Were they able to make it dynamic so that is is "topic" if only one and "topics" if more than one?
