### ISSUE TITLE
Remove "period" from search results

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#922]
When you get results after typing a topic or search, it says, “Results for XXXX.”  You had suggested removing the period.

Issue submitted by Jeannie Sato (AK)

**Comment by breeglej** [comment]
@KellyeDC  - This sounds like an easy fix.  We should just go ahead and do it.  If Glorium says it is not easy, we should reconsider.

**Comment by KellyeDC-zz** [comment]
@svasylenko Is this ready for me to review?

**Comment by svasylenko** [comment]
@KellyeDC yes, please put something to search box.

**Comment by KellyeDC-zz** [comment]
Searched in both environments and very different results.  Also, I did not see the update in DEV.  Was the update pushed to STAGE already?

**Comment by svasylenko** [comment]
@KellyeDC 
Stage (not deployed yet):

![image](https://user-images.githubusercontent.com/46557859/57124878-09e17700-6d90-11e9-880b-ee1bd8ae9121.png)


Dev (already deployed):
![image](https://user-images.githubusercontent.com/46557859/57124904-1bc31a00-6d90-11e9-801a-d3d139b6ccb8.png)

**Comment by KellyeDC-zz** [comment]
@svasylenko This issue remains unresolved.  We can discuss further at your convenience.

**Comment by KellyeDC-zz** [comment]
Ready for PO review.

**Comment by grawdon** [comment]
I don't see a period, so it looks fixed.
