### ISSUE TITLE
Duplicate Personalized Action Plans

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#923]
There are still a lot of problems uploading curated experiences.  We are still getting double PAPs.  (2 “safety planning” or “prepare for hearing”).    (Update – I included you on an email describing my experience today suggesting the extra PAP issue is related to A2J.)

Issue submitted by Jeannie Sato (AK)

**Comment by KellyeDC-zz** [comment]
Is this a valid defect?

**Comment by breeglej** [comment]
@KellyeDC - I would put this in high priority.  We need to fix before pilot.

**Comment by svasylenko** [comment]
We went through whole flow in code and UI and could not reproduce this bug.

**Comment by grawdon** [comment]
@KellyeDC-zz I was not able to reproduce this problem. I have done many PAPs over the past months and have never seen it.
