### ISSUE TITLE
As a system, when a user clicks on an external link, open a new window

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#936]
As a system, when a user clicks on an external link, open a new window

**Comment by KellyeDC-zz** [comment]
Issue resolved.  When a user navigates to an external site, a new window is opened.

Please use the dev environment to confirm.

**Comment by grawdon** [comment]
@KellyeDC Yes, this worked in Dev. Thanks for pointing me to it.
