### ISSUE TITLE
Call the Microsoft API and pull in the "real name" of the resource and the GUID

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#937]
Authors would be able to select the "real name" and the GUID would be inserted into the template in the format needed by the Legal Navigator viewer. Although this enhancement has been completed on the a2J Author side, it has not functioned properly, since the cutover to LSC/Glorium.  

Background: 
Topic_ID* –System-generated unique identifier (ID) for each topic.  Also used to map resources in the Resources Import template to the associated topic.  If a new topic is added this field will remain blank until the Development team generates a new ID for the topic and updates the spreadsheet. Also known as the GUID.

**Comment by breeglej** [comment]
@KellyeDC - I agree that we should do this.  When there is room, we should place it in a sprint.

**Comment by svasylenko** [comment]
https://api-dev.legalnav.org/api/topics-resources/resources?state=AK&topicName=Divorce
https://api-dev.legalnav.org/api/topics-resources/topics?state=AK

**Comment by KellyeDC-zz** [comment]
@svasylenko Are the json files located in the topics and resources table in CosmosDB?

**Comment by JessicaFrank** [comment]
This went live on a2jauthor.org on Tuesday, May 21.

**Comment by grawdon** [comment]
We need to have Jessica show this to us on a call as I don't have A2J Authoring software with which to test it.

**Comment by grawdon** [comment]
@KellyeDC We should ask Jeannie to show us this on the call this PM.

**Comment by grawdon** [comment]
I checked this out in Dev with the script Jeannie gave me and the GUIDs showed up as they should.
