### ISSUE TITLE
Determine WHERE these files should be uploaded to (i.e. url, environment) 

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#940]
Define specifically where we want json files uploaded into Cosmos DB to include environment and specify Legal Navigator url for CALI

**Comment by breeglej** [comment]
@KellyeDC - I marked this as high priority because I think we need to fix all the unfinished or broken things with A2J author as quickly as possible.

**Comment by KellyeDC-zz** [comment]
LSC determined the location for content uploads for guided interviews should be maintained in the stage environment of the Cosmos DB.

**Comment by KellyeDC-zz** [comment]
@johnmayer We need to check with the team to understand the significance of A2J Author knowing the location of json files, maintained in LegalNav.

**Comment by svasylenko** [comment]
![image](https://user-images.githubusercontent.com/46557859/57076131-883b0c00-6cf1-11e9-9c5f-d8b6610b9dcd.png)

**Comment by svasylenko** [comment]
@KellyeDC could you please provide more info in respect whether we should do something or not?

**Comment by KellyeDC-zz** [comment]
Per email sent to Jessica @ CALI, we are just awaiting confirmation on A2J Author's request.  Let's see if the information provided suffices.

**Comment by KellyeDC-zz** [comment]
This task is complete. No testing required.
