### ISSUE TITLE
Create a new A2J Template option that would automatically format the template elements 

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#942]
Create new A2J Template option that would automatically format the template elements in the way the Legal Navigator parser requires for the Personalized Action Plan. It is my understanding that this enhancement was completed in December and requires no further development on either side.

**Comment by KellyeDC-zz** [comment]
According to demo provided by Jeannie Sato (AK Courts), it appears that this functionality has not been deployed.  We need to work with CALI/A2J Author to resolve.

**Comment by breeglej** [comment]
@KellyeDC  - We need to fix this.

**Comment by JessicaFrank** [comment]
Will be in the next A2J Author code push. Expected last week of April/1st week of May.

**Comment by KellyeDC-zz** [comment]
Once confirmed with states, we can close issue.

**Comment by JessicaFrank** [comment]
Code push went live Tuesday, May 21 with the LegalNav element within Templates. States with questions on how to use it can reach out to me (jessica@cali.org)
