### ISSUE TITLE
Revert UI for Guided Assist navigation back to "Yes" and "No" and remove the symbols used for yes/no

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#949]
Revert UI for Guided Assist navigation back to "Yes" and "No" and remove the symbols

See issue #679 and maintain the changes made to the radio buttons.  This is ONLY for the "yes/no" questions in guided assist.

**Comment by svasylenko** [comment]
Already implemented.

![image](https://user-images.githubusercontent.com/46557859/56962701-dcae8200-6b5f-11e9-9d20-ea0a1879a66e.png)


@KellyeDC shall we close this ticket?

**Comment by KellyeDC-zz** [comment]
Assign for Review @svasylenko

**Comment by grawdon** [comment]
This is done
