### ISSUE TITLE
Section: Can Legal Navigator Help me find a lawyer?

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#950]
Issue: Space needed after period at end of first sentence. 

Correction: Add space

Location: 

https://stage.legalnav.org/help
--

**Comment by ozholob** [comment]
Hi @KellyeDC, fixed
![image](https://user-images.githubusercontent.com/55988406/72340337-b79f7680-36d0-11ea-922c-5ea1d6e15ada.png)

**Comment by grawdon** [comment]
@KellyeDC-zz Space is there.
