### ISSUE TITLE
Section: What if I am not in Alaska or Hawaii?

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#951]
Issue: Three external websites are not hyperlinked

Correction: All external websites should be hyperlinked

Location:

 https://stage.legalnav.org/help

**Comment by ozholob** [comment]
Hi @KellyeDC, fixed on dev and stage
![image](https://user-images.githubusercontent.com/55988406/72340030-144e6180-36d0-11ea-917f-ee8695ac94c2.png)

**Comment by grawdon** [comment]
@KellyeDC-zz All hyperlinks are working.
