### ISSUE TITLE
Section: How can I learn more or get involved?

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#952]
Issue: Space needed between contact: and legalnavigadmin@legalnav.org

Correction: Add space

Location: 

https://stage.legalnav.org/help

**Comment by ozholob** [comment]
Hi @KellyeDC, fixed for dev & stage:
![image](https://user-images.githubusercontent.com/55988406/72264569-9e8cbc00-3623-11ea-8e19-0f41806ad45c.png)
Thanks

**Comment by grawdon** [comment]
@KellyeDC-zz Space is there.
