### ISSUE TITLE
Check template for proper ordering/Guided Assistant block should be above the map

### ISSUE THREAD

**Issue by svasylenko** [LSCOIT/LegalNavigator#961]
Guided Assistant block should be above the map, not below. Please check and fix.

![image](https://user-images.githubusercontent.com/46557859/60994190-b3c51d00-a358-11e9-8963-ada852822288.png)

**Comment by Olgaivchenko** [comment]
Steps to reproduce:
1. Go to https://stage.legalnav.org/
2. Choose 'Hawaii'
3. Go to 'Topics & Resources'
4. Go to 'Traffic And Cars'
5. Choose 'Dealing with Traffic and Parking Tickets'

Expected Result: Guided Assistant block should be above the map, not below.

**Comment by Olgaivchenko** [comment]
Done in Sprint 11. Moved to Ready for Review.

**Comment by grawdon** [comment]
Guided assist is appear on top on the right.
