### ISSUE TITLE
A2J has a code “SET [   ] TO TRUE” with a variable name going between the brackets

### ISSUE THREAD

**Issue by Olgaivchenko** [LSCOIT/LegalNavigator#963]
2.	A2J has a code “SET [   ] TO TRUE” with a variable name going between the brackets.  In Step 5, question 5 I have: 
<img width="278" alt="image" src="https://user-images.githubusercontent.com/52704536/61278392-cb6b2e00-a7bc-11e9-8c95-a7795943d862.png">
Step 5, question 6 I have:
<img width="309" alt="image" src="https://user-images.githubusercontent.com/52704536/61278400-d0c87880-a7bc-11e9-8b7c-f0c0b18689ba.png">
I talked to Jessica about this and the code/logic is correct.  But currently Legal Navigator is not reading more than 1 “SET [] TO TRUE” so if a user selected “both” they only get “Other side violated order TF” in their Action Plan.  They also need to get “End protective order TF” in their action plan.  If this cannot be fixed by launch I need to change the interview.  But: Legal Navigator needs to know to read more than 1 “SET [] TO TRUE”

**Comment by Olgaivchenko** [comment]
@KellyeDC hello, Kellye, could you please provide us with the template of such file to reproduce/test this issue? Thanks in advance.

**Comment by konstantin-orekhov** [comment]
07/17 - 2h

**Comment by KellyeDC-zz** [comment]
Please use the latest Protective Order file from Alaska.  It should be in the @content-alaska  channel.

**Comment by konstantin-orekhov** [comment]
07/22 - 5

**Comment by Olgaivchenko** [comment]
Done in Sprint 11. Moved to Ready for Review.
