### ISSUE TITLE
[Protective Order Guided Assist] Letters change on the screen – they jump around, if you click on the middle option

### ISSUE THREAD

**Issue by Olgaivchenko** [LSCOIT/LegalNavigator#966]
5.	Another weird but not substantive issue.  This question is in the Protective Order Guided Assist:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/52704536/61279467-daeb7680-a7be-11e9-8c3d-25dca3680a8f.png">
For some weird reason, if you click on the middle option, the letters change on the screen – they jump around – and then look like this:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/52704536/61279480-dfb02a80-a7be-11e9-9156-6afdb181028b.png">
I haven’t noticed this in any other question.

**Comment by KellyeDC-zz** [comment]
Did someone from LSC prioritize this defect for Sprint 11? @olgaivchenko

**Comment by konstantin-orekhov** [comment]
07/16 - 2h

**Comment by grawdon** [comment]
I did not prioritize this issue.

**Comment by Olgaivchenko** [comment]
> Did someone from LSC prioritize this defect for Sprint 11? @Olgaivchenko

@KellyeDC 
Hello Kellye, 
this issue from Slack, Serhii assigned this to Development Team.
[Defects and issues discovered from June 2019 protective order guided assist.docx](https://github.com/LSCOIT/LegalNavigator/files/3400906/Defects.and.issues.discovered.from.June.2019.protective.order.guided.assist.docx)

So I just set Low priority based on info from message (it was mentioned **_Another weird but not substantive issue_** )
In this case, priorities help to plan work during Sprint, but all issues from Sprint 11 will be fixed.

**Comment by Olgaivchenko** [comment]
Done in Sprint 11. Move to Ready fore Review

**Comment by KellyeDC-zz** [comment]
Ready for PO review

**Comment by grawdon** [comment]
Tested and this was fixed for AK Protective Order in Dev.
