### ISSUE TITLE
Add Status to Topics/Resources spreadsheet uploads for Alaska/Hawaii

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#967]
GUID updates for Topics & Resources, so that new uploads are tagged as ACTIVE/VALID and previous uploads are INACTIVE/INVALID

**Comment by konstantin-orekhov** [comment]
I have deeply investigated this problem. At the moment, the download works like this:
1. Uploading data from excel document.
2. Parsing document
    1. If  GUID found in column document id, we use this GUID, if GUID 
        not present we create new GUID and save the new GUID in the document.
    2. We taking the record with GUID id.   
    2. We search document with GUID in the database, if the document 
        found we update this record, if not found we create a new record.

I think we can't create any duplication in the database if we safe excel file after import document and use one file for a creating and updating records in the database.

**Comment by KellyeDC-zz** [comment]
Decided on a different approach.
