### ISSUE TITLE
Location Based on County

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#970]
As a platform user, I want to enter the county, along with the state to get a more accurate search results based on my location(county).

**Comment by Olgaivchenko** [comment]
Investigation: Size 1

**Comment by KellyeDC-zz** [comment]
Ready for PO Review

**Comment by grawdon** [comment]
County is the same as zip code. I entered "Kunia" for county, changed location, and no resources showed up.

**Comment by yevhenobertas** [comment]
@KellyeDC , The same reason as in #971. Could you please provide valid data for the topic entities, so we can retrieve that based on County? Thank you.

**Comment by KellyeDC-zz** [comment]
As discussed the location should be mapped to resources not topics.  Please let me know if you require further clarity.

Kellye Bennett
Legal Navigator Project Manager
Legal Services Corporation
_____________________________________________________________________
Office of Information Technology
3333 K Street, NW
Washington, DC 20007
P: 202.295.1569
M: 703.889.7288
E: bennettk@lsc.gov
________________________________

**Comment by yevhenobertas** [comment]
@KellyeDC , Fixed in the development environment

**Comment by grawdon** [comment]
@KellyeDC-zz  We decided to use zip codes only for now. AK doesn't use counties and HI believes it is a better location for narrowing resources.
