### ISSUE TITLE
Location Based on Zip Code

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#971]
As a platform user, I want to enter the zip code, along with the state to get a more accurate search results based on my location(zip code).

**Comment by Olgaivchenko** [comment]
Investigation: Size 1

**Comment by KellyeDC-zz** [comment]
Ready for PO review

**Comment by grawdon** [comment]
This seems to be excluding all topics and resources if a zip code is entered from the start. I entered 96701, then went to topics and resources and nothing shows up under any of them. If I enter the more generic "Hawaii", they do show up. This is not the desired behavior for location.

**Comment by yevhenobertas** [comment]
@KellyeDC , The reason of that behavoir is that we don't have valid data in the database. We don't have topic entities with Zip Code value in it. Could you please provide valid data for the topic entities, so we can retrieve that based on Zip Code? Thank you.

**Comment by KellyeDC-zz** [comment]
As discussed, location should be mapped to resources for zip code.  (Same as county)

Kellye Bennett
Legal Navigator Project Manager
Legal Services Corporation
_____________________________________________________________________
Office of Information Technology
3333 K Street, NW
Washington, DC 20007
P: 202.295.1569
M: 703.889.7288
E: bennettk@lsc.gov
________________________________

**Comment by yevhenobertas** [comment]
@KellyeDC , Fixed in the development environment

**Comment by grawdon** [comment]
@KellyeDC-zz Since Alaska does not use zip codes, I could only test for Hawaii. I did two different zip codes and the resources were returned relevant to those zip codes.
