### ISSUE TITLE
Update Topics & Resources Spreadsheet to include Priority/Ranking and ADD field to database

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#972]
For topics/resources content management, add priority/ranking as specified by the states

A. Add the field to the appropriate tables
B. Add field to all spreadsheets
C. Make certain that the field accommodates the data type for priority/rank

NOTE:  Kellye to confirm the data type with the states and the states will prioritize the spreadsheets.  We need to provide the states with the latest uploaded spreadsheets with GUIDs in LSC's Box account.  Let me know if there are any questions.

**Comment by ConstantinOr** [comment]
08/14 - 8h

**Comment by ConstantinOr** [comment]
08/15 - 4h

**Comment by ConstantinOr** [comment]
08/16 - 4h

**Comment by KellyeDC-zz** [comment]
Ready for PO review.
