### ISSUE TITLE
[Incoming resources] Remove button doesn't work 

### ISSUE THREAD

**Issue by Olgaivchenko** [LSCOIT/LegalNavigator#979]
Nothing happened by pressing Remove button.
Perform investigation and fix the issue

**Comment by KellyeDC-zz** [comment]
@svasylenko Where is the REMOVE button referenced here?

**Comment by svasylenko** [comment]
@KellyeDC Kellye, you have to press ... and Remove option is shown

![image](https://user-images.githubusercontent.com/46557859/66641845-35f90200-ec24-11e9-8d18-0ca193dad558.png)


Task is fixed.

**Comment by svasylenko** [comment]
After pressing Remove

![image](https://user-images.githubusercontent.com/46557859/66641927-5759ee00-ec24-11e9-926f-00f60a4b13ad.png)

**Comment by KellyeDC** [comment]
Issue resolved
