### ISSUE TITLE
Divorce/Separation/Annulment Stuck on Location Question in Dev/Stage

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#983]
Platform user is unable to proceed in the guided interview once the location question is asked.  It does not produce an error.  It only returns the same screen when "continue" is selected.

**Comment by yevhenobertas** [comment]
@KellyeDC , We tried to reproduce this issue. And we can't reproduce it. Could you please provide with more information (for example video) & steps to reproduce? Thank you.

I suggest to best way to describe issues and bugs is to use the next example:

Preconditions:

Development environment

Steps to reproduce:

1. Login the application

2. Click on the "" Button

3. Switch to Topics & Resources

4. ....

5. ....

Actual (current) result:

Topic is not visible

Expected (right) result:

Topic should be visible

**Comment by KellyeDC-zz** [comment]
It appears to work fine in DEV, please move to “Ready for Review”. We will request code push for all approved issues shortly.

Kellye Bennett
Legal Navigator Project Manager
Legal Services Corporation
_____________________________________________________________________
Office of Information Technology
3333 K Street, NW
Washington, DC 20007
P: 202.295.1569
M: 703.889.7288
E: bennettk@lsc.gov
________________________________

**Comment by grawdon** [comment]
I agree. This was fixed for me in Dev. I moved on from location when I chose several locations and could always move forward.
