### ISSUE TITLE
Update PROD Environment: Code Push

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#984]
Update PROD Environment: Code Push

**Comment by grawdon** [comment]
@KellyeDC Prod is up and running, but the Guided Assists are not working. How functional does this issue need to be to be resolved.

**Comment by grawdon** [comment]
@KellyeDC-zz  Again, I don't find I heard back from you on this.

**Comment by grawdon** [comment]
Prod is up and working. There is still a problem with AK guided assistants, but that is not confined to PROD.
