### ISSUE TITLE
Create Data Export of resourceType and it's properties

### ISSUE THREAD

**Issue by yevhenobertas** [LSCOIT/LegalNavigator#992]
Create Data Export of resourceType and it's properties

**Comment by grawdon** [comment]
@KellyeDC Let's discuss this too. I didn't see a new export function, only the new import function.

**Comment by grawdon** [comment]
@KellyeDC Is this in the admin panel? I'm not sure how I'm supposed to test.

**Comment by grawdon** [comment]
@KellyeDC-zz I never heard back from you on this.

**Comment by KellyeDC** [comment]
PO review not required.
