### ISSUE TITLE
The heading of the paragraph overlaps the text under the paragraph

### ISSUE THREAD

**Issue by yevhenobertas** [LSCOIT/LegalNavigator#994]
Staging
The heading of the paragraph overlaps the text under the paragraph
Fixed on dev env.

![LNav_styling](https://user-images.githubusercontent.com/48689437/66125262-2dcf1000-e5ef-11e9-927c-b57b6bf15e08.png)

**Comment by KellyeDC-zz** [comment]
@yevhenobertas Is this for articles resourceType?, specifically related to Hawaii content?

**Comment by yevhenobertas** [comment]
[](url)

**Comment by yevhenobertas** [comment]
> @yevhenobertas Is this for articles resourceType?, specifically related to Hawaii content?

@KellyeDC , Yes, it's for articles resourceType, specifically to Hawaii content. I have added the screenshot to description of this ticket.
